/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/magic/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a magic-link sign-in email
         * @description Generates a single-use sign-in token and emails it to the address.
         *     Always returns 202 — the response is identical whether or not the
         *     email is registered, so an attacker can't enumerate accounts.
         *
         *     Layered rate limits: per-IP (existing 20/min auth limiter) and
         *     per-email (3 / 15 min, enforced in the service against the DB).
         */
        post: operations["requestMagicLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/{locationId}/competitions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Location UUID. */
                locationId: components["parameters"]["LocationId"];
            };
            cookie?: never;
        };
        /** List competitions at a location */
        get: operations["listCompetitions"];
        put?: never;
        /**
         * Create a competition
         * @description Requires `head_setter+` role at the location.
         */
        post: operations["createCompetition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/by-slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The comp's URL-safe slug. Resolved across every location the
                 *     authenticated user has membership at; first match wins. Use
                 *     this when the SPA has a slug from a magic-link URL but no
                 *     location context.
                 */
                slug: string;
            };
            cookie?: never;
        };
        /** Resolve a competition by slug across the user's locations */
        get: operations["getCompetitionBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition UUID. */
                id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        /** Get a competition by id */
        get: operations["getCompetition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a competition
         * @description Requires `head_setter+` role at the comp's location. All fields
         *     are optional; only provided fields are updated.
         */
        patch: operations["updateCompetition"];
        trace?: never;
    };
    "/competitions/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition UUID. */
                id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        /** List events under a competition (sequence ASC) */
        get: operations["listEvents"];
        put?: never;
        /**
         * Create an event under a competition
         * @description Requires `head_setter+` role at the comp's location.
         */
        post: operations["createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition event UUID. */
                id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update an event
         * @description Requires `head_setter+` role at the comp's location.
         */
        patch: operations["updateEvent"];
        trace?: never;
    };
    "/competitions/{id}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition UUID. */
                id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        /** List categories under a competition (sort order ASC) */
        get: operations["listCategories"];
        put?: never;
        /**
         * Create a category
         * @description Requires `head_setter+` role at the comp's location.
         */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}/problems": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition event UUID. */
                id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        /** List problems under an event (sort order ASC) */
        get: operations["listProblems"];
        put?: never;
        /**
         * Create a problem under an event
         * @description Requires `head_setter+` role at the comp's location.
         */
        post: operations["createProblem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problems/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition problem UUID. */
                id: components["parameters"]["ProblemId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a problem
         * @description Requires `head_setter+` role at the comp's location.
         */
        patch: operations["updateProblem"];
        trace?: never;
    };
    "/competitions/{id}/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition UUID. */
                id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        /**
         * List registrations for a competition
         * @description Any authenticated user can list. The leaderboard-visibility
         *     filter (wave 4) governs how much detail unaffiliated users see.
         */
        get: operations["listRegistrations"];
        put?: never;
        /**
         * Register self (or another climber, if staff) for a competition
         * @description With no `user_id` field, registers the calling user. Staff
         *     (`gym_manager+` at the comp's location) may pass a `user_id`
         *     to register someone else.
         */
        post: operations["createRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registrations/{id}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition registration UUID. */
                id: components["parameters"]["RegistrationId"];
            };
            cookie?: never;
        };
        /**
         * Per-problem state for a registration
         * @description Returns the climber's current per-problem attempt state, in the
         *     same shape the action endpoint emits. Used by the SPA scorecard
         *     to hydrate on first load (and after a refresh).
         *
         *     Caller must be the registration's user OR `gym_manager+` at the
         *     comp's location.
         */
        get: operations["listRegistrationAttempts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registrations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition registration UUID. */
                id: components["parameters"]["RegistrationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Withdraw a registration (mark withdrawn)
         * @description Caller must be the registration's user OR `gym_manager+` at the
         *     comp's location. Soft delete — the row stays for audit, the bib
         *     number is freed for reuse.
         */
        delete: operations["withdrawRegistration"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition UUID. */
                id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit one or more attempt actions
         * @description Unified write endpoint for the climber's scorecard. Each action
         *     is independent and idempotent — accidental retries from a
         *     flaky-network phone replay safely. Actions are processed in
         *     order; failures don't abort the batch.
         *
         *     Action types:
         *     - `increment` — add an attempt (you tried again)
         *     - `zone` — mark zone reached at the current attempt count
         *     - `top` — mark sent (implicitly marks zone if not already)
         *     - `undo` — revert to the state before the most recent log entry
         *     - `reset` — zero everything for this problem (climber within
         *       grace window, or staff)
         *
         *     Idempotency: send a UUID `idempotency_key` per action. Server
         *     dedupes against `competition_attempt_log`; replay returns the
         *     cached result.
         *
         *     Authorization: caller must own the registration. Server rejects
         *     actions whose problem belongs to an event whose `ends_at` has
         *     passed (rejected with reason `event_closed`).
         */
        post: operations["submitActions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts/{id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition attempt UUID. */
                id: components["parameters"]["AttemptId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stamp an attempt as verified
         * @description Setter+ at the comp's location signs off on a climber's recorded
         *     attempt. Sets `verified_by` + `verified_at` on the attempt; does
         *     not modify scoring fields.
         */
        post: operations["verifyAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts/{id}/override": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition attempt UUID. */
                id: components["parameters"]["AttemptId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace an attempt's state directly
         * @description Setter+ at the comp's location forcibly sets the attempt state.
         *     Use cases: late-night cleanup, dispute resolution, recording an
         *     attempt that was missed in real time. The override is logged
         *     with `action=override` and the actor's user id, so the audit
         *     trail shows what staff did.
         */
        post: operations["overrideAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{id}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition UUID. */
                id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        /**
         * Get the comp leaderboard
         * @description Computes and returns the comp leaderboard using the active
         *     scorer (`competitions.scoring_rule`). Optional `category` query
         *     filter narrows to one category; otherwise returns ranks per
         *     registration regardless of category (set staff expectations:
         *     for multi-category comps you usually want one query per
         *     category to get separated standings).
         *
         *     Response is cached server-side for ~2 seconds; cache is
         *     invalidated whenever an action lands on the comp.
         */
        get: operations["getLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{id}/leaderboard/stream": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition UUID. */
                id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        /**
         * Live leaderboard via Server-Sent Events
         * @description Long-lived `text/event-stream` connection. Server emits a
         *     `leaderboard` event on connect (initial snapshot) and another
         *     `leaderboard` event after every action / verify / override on
         *     the comp. A `: keepalive` comment is emitted every 30 seconds
         *     so reverse proxies don't kill idle connections.
         *
         *     Browsers consume via `EventSource`:
         *
         *     ```js
         *     const es = new EventSource(`/api/v1/competitions/${id}/leaderboard/stream`);
         *     es.addEventListener('leaderboard', e => {
         *       const board = JSON.parse(e.data);
         *       // …re-render…
         *     });
         *     ```
         *
         *     The handler closes the stream cleanly on client disconnect
         *     (browser tab closed, or `es.close()`).
         *
         *     OpenAPI 3.0 doesn't model SSE responses well; the response
         *     schema below describes the **payload of each `leaderboard`
         *     event**, not the wire format itself.
         */
        get: operations["streamLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "error": "competition not found"
         *     }
         */
        Error: {
            /** @description Human-readable error message. Matches the existing routewerk envelope. */
            error: string;
        };
        /**
         * @example {
         *       "ok": true
         *     }
         */
        Accepted: {
            ok: boolean;
        };
        /**
         * @example {
         *       "email": "climber@example.com",
         *       "next": "/comp/league-2026"
         *     }
         */
        MagicLinkRequest: {
            /**
             * Format: email
             * @description The address to receive the sign-in link.
             */
            email: string;
            /**
             * @description Optional path to redirect to after successful verification.
             *     Must be a relative path (no scheme, no host) — server validates
             *     via `safeRedirect` and falls back to `/dashboard` if invalid.
             * @example /comp/league-2026
             */
            next?: string;
        };
        /**
         * @description Comp shape. `single` = one event, `series` = multiple events
         *     whose results combine per `aggregation`.
         * @enum {string}
         */
        CompetitionFormat: "single" | "series";
        /** @enum {string} */
        CompetitionStatus: "draft" | "open" | "live" | "closed" | "archived";
        /**
         * @description Who can see the leaderboard:
         *     - `public` — anyone (default; matches LEF/Mosaic league plan)
         *     - `members` — anyone with org membership at the comp's location
         *     - `registrants` — only climbers registered for this comp
         * @enum {string}
         */
        LeaderboardVisibility: "public" | "members" | "registrants";
        /**
         * @description How per-event scores combine into a comp-level standing. Stored
         *     as freeform jsonb in the DB; this is the canonical decoded form.
         *     Method-specific fields (`drop`, `weights`, `finals_event_id`,
         *     `best_n`) are only meaningful for some methods.
         */
        Aggregation: {
            /** @enum {string} */
            method?: "sum" | "sum_drop_n" | "weighted_finals" | "best_n";
            /** @description For `sum_drop_n`/`best_n`: number of low events to discard. */
            drop?: number;
            /** @description For `weighted_finals`: parallel to event sequence. */
            weights?: number[];
            /**
             * Format: uuid
             * @description For `weighted_finals`: which event is the finals.
             */
            finals_event_id?: string;
            /** @description For `best_n`: keep this many top per-event scores. */
            best_n?: number;
        };
        Competition: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            location_id: string;
            name: string;
            /** @description URL-safe identifier, unique per location. */
            slug: string;
            format: components["schemas"]["CompetitionFormat"];
            aggregation: components["schemas"]["Aggregation"];
            /**
             * @description Name of the scorer to apply. Built-ins: `top_zone`, `fixed`,
             *     `decay`. Per-event overrides live on `competition_events`.
             */
            scoring_rule: string;
            /** @description Scorer-specific config (shape depends on `scoring_rule`). */
            scoring_config: {
                [key: string]: unknown;
            };
            status: components["schemas"]["CompetitionStatus"];
            leaderboard_visibility: components["schemas"]["LeaderboardVisibility"];
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
            /** Format: date-time */
            registration_opens_at?: string | null;
            /** Format: date-time */
            registration_closes_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CompetitionCreate: {
            name: string;
            /** @description Lowercase, digits, and hyphens; must start with alphanumeric. */
            slug: string;
            format: components["schemas"]["CompetitionFormat"];
            aggregation?: components["schemas"]["Aggregation"];
            scoring_rule: string;
            scoring_config?: {
                [key: string]: unknown;
            };
            /** @description Defaults to `draft` if omitted. */
            status?: components["schemas"]["CompetitionStatus"];
            /** @description Defaults to `public` if omitted. */
            leaderboard_visibility?: components["schemas"]["LeaderboardVisibility"];
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
            /** Format: date-time */
            registration_opens_at?: string | null;
            /** Format: date-time */
            registration_closes_at?: string | null;
        };
        /**
         * @description All fields optional. Only fields present in the request are
         *     updated. To clear a nullable field, send explicit null.
         */
        CompetitionUpdate: {
            name?: string;
            slug?: string;
            format?: components["schemas"]["CompetitionFormat"];
            aggregation?: components["schemas"]["Aggregation"];
            scoring_rule?: string;
            scoring_config?: {
                [key: string]: unknown;
            };
            status?: components["schemas"]["CompetitionStatus"];
            leaderboard_visibility?: components["schemas"]["LeaderboardVisibility"];
            /** Format: date-time */
            starts_at?: string;
            /** Format: date-time */
            ends_at?: string;
            /** Format: date-time */
            registration_opens_at?: string | null;
            /** Format: date-time */
            registration_closes_at?: string | null;
        };
        CompetitionEvent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            competition_id: string;
            name: string;
            /** @description Position within the comp; unique per comp. */
            sequence: number;
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
            /** @description Multiplier when aggregating event scores into a series total. */
            weight: number;
            /**
             * @description If set, overrides the comp-level scoring_rule for this event.
             *     NULL means "use the comp default". Lets a series mix event types
             *     (boulder + speed + lead under one comp).
             */
            scoring_rule_override?: string | null;
            scoring_config_override?: {
                [key: string]: unknown;
            } | null;
        };
        EventCreate: {
            name: string;
            sequence: number;
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
            /** @description Defaults to 1.0 if omitted. */
            weight?: number;
            scoring_rule_override?: string;
            scoring_config_override?: {
                [key: string]: unknown;
            };
        };
        /** @description All fields optional; only provided fields are updated. */
        EventUpdate: {
            name?: string;
            sequence?: number;
            /** Format: date-time */
            starts_at?: string;
            /** Format: date-time */
            ends_at?: string;
            weight?: number;
            scoring_rule_override?: string | null;
            scoring_config_override?: {
                [key: string]: unknown;
            } | null;
        };
        CompetitionCategory: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            competition_id: string;
            name: string;
            sort_order: number;
            /**
             * @description Freeform jsonb describing eligibility (age band, gender, etc.).
             *     Shape is intentionally open — staff define what makes sense
             *     per comp.
             */
            rules: {
                [key: string]: unknown;
            };
        };
        CategoryCreate: {
            name: string;
            /** @description Defaults to 0 if omitted. */
            sort_order?: number;
            rules?: {
                [key: string]: unknown;
            };
        };
        CompetitionProblem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            event_id: string;
            /**
             * Format: uuid
             * @description Optional link to a routes table row (gym inventory).
             */
            route_id?: string | null;
            /** @description Short identifier shown to climbers (e.g. "M1", "B7"). */
            label: string;
            /** @description Used by `fixed` scorer; ignored by `top_zone` and `decay`. */
            points?: number | null;
            zone_points?: number | null;
            grade?: string | null;
            color?: string | null;
            sort_order: number;
        };
        ProblemCreate: {
            /** Format: uuid */
            route_id?: string | null;
            label: string;
            points?: number | null;
            zone_points?: number | null;
            grade?: string | null;
            color?: string | null;
            sort_order?: number;
        };
        /** @description All fields optional; only provided fields are updated. */
        ProblemUpdate: {
            /** Format: uuid */
            route_id?: string | null;
            label?: string;
            points?: number | null;
            zone_points?: number | null;
            grade?: string | null;
            color?: string | null;
            sort_order?: number;
        };
        CompetitionRegistration: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            competition_id: string;
            /** Format: uuid */
            category_id: string;
            /** Format: uuid */
            user_id: string;
            /** @description Snapshot at registration time. */
            display_name: string;
            bib_number?: number | null;
            /** Format: date-time */
            waiver_signed_at?: string | null;
            /** Format: date-time */
            paid_at?: string | null;
            /** Format: date-time */
            withdrawn_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        RegistrationCreate: {
            /** Format: uuid */
            category_id: string;
            /**
             * Format: uuid
             * @description Optional. Defaults to the calling user. Setting a different
             *     user_id requires `gym_manager+` role at the comp's location.
             */
            user_id?: string;
            /** @description Optional. Defaults to the user's display_name. */
            display_name?: string;
            /** @description Staff-assigned bib. Climbers self-registering should leave null. */
            bib_number?: number | null;
        };
        /** @enum {string} */
        ActionType: "increment" | "zone" | "top" | "undo" | "reset";
        ActionItem: {
            /**
             * Format: uuid
             * @description Strongly recommended; UUIDv4 generated client-side. Server
             *     dedupes accidental retries (action queue + flaky network).
             */
            idempotency_key?: string;
            type: components["schemas"]["ActionType"];
            /** Format: uuid */
            problem_id: string;
            /**
             * Format: date-time
             * @description Optional; recorded but not used for ordering.
             */
            client_timestamp?: string;
        };
        ActionsRequest: {
            actions: components["schemas"]["ActionItem"][];
        };
        AttemptState: {
            /** Format: uuid */
            problem_id: string;
            attempts: number;
            zone_attempts?: number | null;
            zone_reached: boolean;
            top_reached: boolean;
        };
        ActionApplied: {
            /** Format: uuid */
            idempotency_key?: string;
            /** Format: uuid */
            problem_id: string;
            state: components["schemas"]["AttemptState"];
            /** @description True if this action's idempotency key matched a prior request. */
            replayed?: boolean;
        };
        ActionRejected: {
            /** Format: uuid */
            idempotency_key?: string;
            /** Format: uuid */
            problem_id: string;
            /** @enum {string} */
            reason: "unknown_problem" | "wrong_competition" | "event_closed" | "no_history" | "server_error";
        };
        ActionsResponse: {
            applied: components["schemas"]["ActionApplied"][];
            rejected: components["schemas"]["ActionRejected"][];
            /** @description Current state for every problem touched by this batch. */
            state: components["schemas"]["AttemptState"][];
        };
        CompetitionAttempt: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            registration_id: string;
            /** Format: uuid */
            problem_id: string;
            attempts: number;
            zone_attempts?: number | null;
            zone_reached: boolean;
            top_reached: boolean;
            notes?: string | null;
            /** Format: date-time */
            logged_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: uuid */
            verified_by?: string | null;
            /** Format: date-time */
            verified_at?: string | null;
        };
        /**
         * @description Body for POST /attempts/{id}/override. The fields here
         *     wholesale replace the attempt's state — staff is asserting
         *     "this attempt is now exactly this." A log entry is appended
         *     with action=override.
         */
        AttemptOverride: {
            attempts: number;
            zone_attempts?: number | null;
            zone_reached: boolean;
            top_reached: boolean;
            notes?: string | null;
        };
        Leaderboard: {
            /** Format: uuid */
            competition_id: string;
            /**
             * Format: uuid
             * @description NULL when the leaderboard spans all categories.
             */
            category_id?: string | null;
            scoring_rule: string;
            /** Format: date-time */
            generated_at: string;
            entries: components["schemas"]["LeaderboardEntry"][];
        };
        LeaderboardEntry: {
            /** @description 1-indexed; ties share the lower rank (1224 ranking). */
            rank: number;
            /** Format: uuid */
            registration_id: string;
            display_name: string;
            bib_number?: number | null;
            /** Format: uuid */
            category_id?: string;
            /**
             * @description Aggregate score from the comp's scorer. Used by `fixed`
             *     and `decay`; `top_zone` ranks on (tops, zones, attempts)
             *     and leaves this at 0.
             */
            points: number;
            tops: number;
            zones: number;
            attempts_to_top: number;
            attempts_to_zone: number;
        };
    };
    responses: {
        /** @description Malformed request body or invalid arguments. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated but not allowed to perform this action. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Location UUID. */
        LocationId: string;
        /** @description Competition UUID. */
        CompetitionId: string;
        /** @description Competition event UUID. */
        EventId: string;
        /** @description Competition problem UUID. */
        ProblemId: string;
        /** @description Competition registration UUID. */
        RegistrationId: string;
        /** @description Competition attempt UUID. */
        AttemptId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    requestMagicLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkRequest"];
            };
        };
        responses: {
            /** @description Request accepted (email send happens via background queue). */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
        };
    };
    listCompetitions: {
        parameters: {
            query?: {
                /** @description Filter by status (e.g. `live`, `open`). Omit to include all statuses. */
                status?: components["schemas"]["CompetitionStatus"];
            };
            header?: never;
            path: {
                /** @description Location UUID. */
                locationId: components["parameters"]["LocationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of competitions, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competition"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createCompetition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Location UUID. */
                locationId: components["parameters"]["LocationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompetitionCreate"];
            };
        };
        responses: {
            /** @description Competition created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competition"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Slug already in use at this location. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCompetitionBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The comp's URL-safe slug. Resolved across every location the
                 *     authenticated user has membership at; first match wins. Use
                 *     this when the SPA has a slug from a magic-link URL but no
                 *     location context.
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The competition. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competition"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getCompetition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition UUID. */
                id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The competition. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competition"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateCompetition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition UUID. */
                id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompetitionUpdate"];
            };
        };
        responses: {
            /** @description Updated competition. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competition"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition UUID. */
                id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Events ordered by sequence. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionEvent"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition UUID. */
                id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description Event created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionEvent"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition event UUID. */
                id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventUpdate"];
            };
        };
        responses: {
            /** @description Updated event. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionEvent"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition UUID. */
                id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categories. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionCategory"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition UUID. */
                id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Category created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionCategory"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listProblems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition event UUID. */
                id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problems. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionProblem"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createProblem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition event UUID. */
                id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProblemCreate"];
            };
        };
        responses: {
            /** @description Problem created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionProblem"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateProblem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition problem UUID. */
                id: components["parameters"]["ProblemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProblemUpdate"];
            };
        };
        responses: {
            /** @description Updated problem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionProblem"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listRegistrations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition UUID. */
                id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registrations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionRegistration"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition UUID. */
                id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrationCreate"];
            };
        };
        responses: {
            /** @description Registration created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionRegistration"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Climber already registered for this competition. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listRegistrationAttempts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition registration UUID. */
                id: components["parameters"]["RegistrationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-problem attempt state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptState"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    withdrawRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition registration UUID. */
                id: components["parameters"]["RegistrationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Withdrawn. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    submitActions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition UUID. */
                id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionsRequest"];
            };
        };
        responses: {
            /**
             * @description Per-action results plus the resulting attempt state for every
             *     problem touched by this batch.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    verifyAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition attempt UUID. */
                id: components["parameters"]["AttemptId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated attempt. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionAttempt"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    overrideAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition attempt UUID. */
                id: components["parameters"]["AttemptId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttemptOverride"];
            };
        };
        responses: {
            /** @description Updated attempt. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionAttempt"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getLeaderboard: {
        parameters: {
            query?: {
                /** @description Optional category UUID to filter rankings. */
                category?: string;
            };
            header?: never;
            path: {
                /** @description Competition UUID. */
                id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Computed leaderboard. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Leaderboard"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    streamLeaderboard: {
        parameters: {
            query?: {
                /** @description Optional category UUID to filter the streamed leaderboard. */
                category?: string;
            };
            header?: never;
            path: {
                /** @description Competition UUID. */
                id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Established event stream. Each `leaderboard` event has a
             *     JSON `data:` payload matching the `Leaderboard` schema.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["Leaderboard"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
