/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/magic/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a magic-link sign-in email
         * @description Generates a single-use sign-in token and emails it to the address.
         *     Always returns 202 — the response is identical whether or not the
         *     email is registered, so an attacker can't enumerate accounts.
         *
         *     Layered rate limits: per-IP (existing 20/min auth limiter) and
         *     per-email (3 / 15 min, enforced in the service against the DB).
         */
        post: operations["requestMagicLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/{locationId}/competitions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Location UUID. */
                locationId: components["parameters"]["LocationId"];
            };
            cookie?: never;
        };
        /** List competitions at a location */
        get: operations["listCompetitions"];
        put?: never;
        /**
         * Create a competition
         * @description Requires `gym_manager+` role at the location.
         */
        post: operations["createCompetition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition UUID. */
                id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        /** Get a competition by id */
        get: operations["getCompetition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a competition
         * @description Requires `gym_manager+` role at the comp's location. All fields
         *     are optional; only provided fields are updated.
         */
        patch: operations["updateCompetition"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "error": "competition not found"
         *     }
         */
        Error: {
            /** @description Human-readable error message. Matches the existing routewerk envelope. */
            error: string;
        };
        /**
         * @example {
         *       "ok": true
         *     }
         */
        Accepted: {
            ok: boolean;
        };
        /**
         * @example {
         *       "email": "climber@example.com",
         *       "next": "/comp/league-2026"
         *     }
         */
        MagicLinkRequest: {
            /**
             * Format: email
             * @description The address to receive the sign-in link.
             */
            email: string;
            /**
             * @description Optional path to redirect to after successful verification.
             *     Must be a relative path (no scheme, no host) — server validates
             *     via `safeRedirect` and falls back to `/dashboard` if invalid.
             * @example /comp/league-2026
             */
            next?: string;
        };
        /**
         * @description Comp shape. `single` = one event, `series` = multiple events
         *     whose results combine per `aggregation`.
         * @enum {string}
         */
        CompetitionFormat: "single" | "series";
        /** @enum {string} */
        CompetitionStatus: "draft" | "open" | "live" | "closed" | "archived";
        /**
         * @description Who can see the leaderboard:
         *     - `public` — anyone (default; matches LEF/Mosaic league plan)
         *     - `members` — anyone with org membership at the comp's location
         *     - `registrants` — only climbers registered for this comp
         * @enum {string}
         */
        LeaderboardVisibility: "public" | "members" | "registrants";
        /**
         * @description How per-event scores combine into a comp-level standing. Stored
         *     as freeform jsonb in the DB; this is the canonical decoded form.
         *     Method-specific fields (`drop`, `weights`, `finals_event_id`,
         *     `best_n`) are only meaningful for some methods.
         */
        Aggregation: {
            /** @enum {string} */
            method?: "sum" | "sum_drop_n" | "weighted_finals" | "best_n";
            /** @description For `sum_drop_n`/`best_n`: number of low events to discard. */
            drop?: number;
            /** @description For `weighted_finals`: parallel to event sequence. */
            weights?: number[];
            /**
             * Format: uuid
             * @description For `weighted_finals`: which event is the finals.
             */
            finals_event_id?: string;
            /** @description For `best_n`: keep this many top per-event scores. */
            best_n?: number;
        };
        Competition: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            location_id: string;
            name: string;
            /** @description URL-safe identifier, unique per location. */
            slug: string;
            format: components["schemas"]["CompetitionFormat"];
            aggregation: components["schemas"]["Aggregation"];
            /**
             * @description Name of the scorer to apply. Built-ins: `top_zone`, `fixed`,
             *     `decay`. Per-event overrides live on `competition_events`.
             */
            scoring_rule: string;
            /** @description Scorer-specific config (shape depends on `scoring_rule`). */
            scoring_config: {
                [key: string]: unknown;
            };
            status: components["schemas"]["CompetitionStatus"];
            leaderboard_visibility: components["schemas"]["LeaderboardVisibility"];
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
            /** Format: date-time */
            registration_opens_at?: string | null;
            /** Format: date-time */
            registration_closes_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CompetitionCreate: {
            name: string;
            /** @description Lowercase, digits, and hyphens; must start with alphanumeric. */
            slug: string;
            format: components["schemas"]["CompetitionFormat"];
            aggregation?: components["schemas"]["Aggregation"];
            scoring_rule: string;
            scoring_config?: {
                [key: string]: unknown;
            };
            /** @description Defaults to `draft` if omitted. */
            status?: components["schemas"]["CompetitionStatus"];
            /** @description Defaults to `public` if omitted. */
            leaderboard_visibility?: components["schemas"]["LeaderboardVisibility"];
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
            /** Format: date-time */
            registration_opens_at?: string | null;
            /** Format: date-time */
            registration_closes_at?: string | null;
        };
        /**
         * @description All fields optional. Only fields present in the request are
         *     updated. To clear a nullable field, send explicit null.
         */
        CompetitionUpdate: {
            name?: string;
            slug?: string;
            format?: components["schemas"]["CompetitionFormat"];
            aggregation?: components["schemas"]["Aggregation"];
            scoring_rule?: string;
            scoring_config?: {
                [key: string]: unknown;
            };
            status?: components["schemas"]["CompetitionStatus"];
            leaderboard_visibility?: components["schemas"]["LeaderboardVisibility"];
            /** Format: date-time */
            starts_at?: string;
            /** Format: date-time */
            ends_at?: string;
            /** Format: date-time */
            registration_opens_at?: string | null;
            /** Format: date-time */
            registration_closes_at?: string | null;
        };
    };
    responses: {
        /** @description Malformed request body or invalid arguments. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated but not allowed to perform this action. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Location UUID. */
        LocationId: string;
        /** @description Competition UUID. */
        CompetitionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    requestMagicLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkRequest"];
            };
        };
        responses: {
            /** @description Request accepted (email send happens via background queue). */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
        };
    };
    listCompetitions: {
        parameters: {
            query?: {
                /** @description Filter by status (e.g. `live`, `open`). Omit to include all statuses. */
                status?: components["schemas"]["CompetitionStatus"];
            };
            header?: never;
            path: {
                /** @description Location UUID. */
                locationId: components["parameters"]["LocationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of competitions, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competition"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createCompetition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Location UUID. */
                locationId: components["parameters"]["LocationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompetitionCreate"];
            };
        };
        responses: {
            /** @description Competition created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competition"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Slug already in use at this location. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCompetition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition UUID. */
                id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The competition. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competition"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateCompetition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competition UUID. */
                id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompetitionUpdate"];
            };
        };
        responses: {
            /** @description Updated competition. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competition"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
