// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
	CookieAuthScopes cookieAuthContextKey = "cookieAuth.Scopes"
)

// Defines values for ActionRejectedReason.
const (
	EventClosed      ActionRejectedReason = "event_closed"
	NoHistory        ActionRejectedReason = "no_history"
	ServerError      ActionRejectedReason = "server_error"
	UnknownProblem   ActionRejectedReason = "unknown_problem"
	WrongCompetition ActionRejectedReason = "wrong_competition"
)

// Valid indicates whether the value is a known member of the ActionRejectedReason enum.
func (e ActionRejectedReason) Valid() bool {
	switch e {
	case EventClosed:
		return true
	case NoHistory:
		return true
	case ServerError:
		return true
	case UnknownProblem:
		return true
	case WrongCompetition:
		return true
	default:
		return false
	}
}

// Defines values for ActionType.
const (
	Increment ActionType = "increment"
	Reset     ActionType = "reset"
	Top       ActionType = "top"
	Undo      ActionType = "undo"
	Zone      ActionType = "zone"
)

// Valid indicates whether the value is a known member of the ActionType enum.
func (e ActionType) Valid() bool {
	switch e {
	case Increment:
		return true
	case Reset:
		return true
	case Top:
		return true
	case Undo:
		return true
	case Zone:
		return true
	default:
		return false
	}
}

// Defines values for AggregationMethod.
const (
	BestN          AggregationMethod = "best_n"
	Sum            AggregationMethod = "sum"
	SumDropN       AggregationMethod = "sum_drop_n"
	WeightedFinals AggregationMethod = "weighted_finals"
)

// Valid indicates whether the value is a known member of the AggregationMethod enum.
func (e AggregationMethod) Valid() bool {
	switch e {
	case BestN:
		return true
	case Sum:
		return true
	case SumDropN:
		return true
	case WeightedFinals:
		return true
	default:
		return false
	}
}

// Defines values for CompetitionFormat.
const (
	Series CompetitionFormat = "series"
	Single CompetitionFormat = "single"
)

// Valid indicates whether the value is a known member of the CompetitionFormat enum.
func (e CompetitionFormat) Valid() bool {
	switch e {
	case Series:
		return true
	case Single:
		return true
	default:
		return false
	}
}

// Defines values for CompetitionStatus.
const (
	Archived CompetitionStatus = "archived"
	Closed   CompetitionStatus = "closed"
	Draft    CompetitionStatus = "draft"
	Live     CompetitionStatus = "live"
	Open     CompetitionStatus = "open"
)

// Valid indicates whether the value is a known member of the CompetitionStatus enum.
func (e CompetitionStatus) Valid() bool {
	switch e {
	case Archived:
		return true
	case Closed:
		return true
	case Draft:
		return true
	case Live:
		return true
	case Open:
		return true
	default:
		return false
	}
}

// Defines values for LeaderboardVisibility.
const (
	Members     LeaderboardVisibility = "members"
	Public      LeaderboardVisibility = "public"
	Registrants LeaderboardVisibility = "registrants"
)

// Valid indicates whether the value is a known member of the LeaderboardVisibility enum.
func (e LeaderboardVisibility) Valid() bool {
	switch e {
	case Members:
		return true
	case Public:
		return true
	case Registrants:
		return true
	default:
		return false
	}
}

// Accepted defines model for Accepted.
type Accepted struct {
	Ok bool `json:"ok"`
}

// ActionApplied defines model for ActionApplied.
type ActionApplied struct {
	IdempotencyKey *openapi_types.UUID `json:"idempotency_key,omitempty"`
	ProblemId      openapi_types.UUID  `json:"problem_id"`

	// Replayed True if this action's idempotency key matched a prior request.
	Replayed *bool        `json:"replayed,omitempty"`
	State    AttemptState `json:"state"`
}

// ActionItem defines model for ActionItem.
type ActionItem struct {
	// ClientTimestamp Optional; recorded but not used for ordering.
	ClientTimestamp *time.Time `json:"client_timestamp,omitempty"`

	// IdempotencyKey Strongly recommended; UUIDv4 generated client-side. Server
	// dedupes accidental retries (action queue + flaky network).
	IdempotencyKey *openapi_types.UUID `json:"idempotency_key,omitempty"`
	ProblemId      openapi_types.UUID  `json:"problem_id"`
	Type           ActionType          `json:"type"`
}

// ActionRejected defines model for ActionRejected.
type ActionRejected struct {
	IdempotencyKey *openapi_types.UUID  `json:"idempotency_key,omitempty"`
	ProblemId      openapi_types.UUID   `json:"problem_id"`
	Reason         ActionRejectedReason `json:"reason"`
}

// ActionRejectedReason defines model for ActionRejected.Reason.
type ActionRejectedReason string

// ActionType defines model for ActionType.
type ActionType string

// ActionsRequest defines model for ActionsRequest.
type ActionsRequest struct {
	Actions []ActionItem `json:"actions"`
}

// ActionsResponse defines model for ActionsResponse.
type ActionsResponse struct {
	Applied  []ActionApplied  `json:"applied"`
	Rejected []ActionRejected `json:"rejected"`

	// State Current state for every problem touched by this batch.
	State []AttemptState `json:"state"`
}

// Aggregation How per-event scores combine into a comp-level standing. Stored
// as freeform jsonb in the DB; this is the canonical decoded form.
// Method-specific fields (`drop`, `weights`, `finals_event_id`,
// `best_n`) are only meaningful for some methods.
type Aggregation struct {
	// BestN For `best_n`: keep this many top per-event scores.
	BestN *int `json:"best_n,omitempty"`

	// Drop For `sum_drop_n`/`best_n`: number of low events to discard.
	Drop *int `json:"drop,omitempty"`

	// FinalsEventId For `weighted_finals`: which event is the finals.
	FinalsEventId *openapi_types.UUID `json:"finals_event_id,omitempty"`
	Method        *AggregationMethod  `json:"method,omitempty"`

	// Weights For `weighted_finals`: parallel to event sequence.
	Weights *[]int `json:"weights,omitempty"`
}

// AggregationMethod defines model for Aggregation.Method.
type AggregationMethod string

// AttemptState defines model for AttemptState.
type AttemptState struct {
	Attempts     int                `json:"attempts"`
	ProblemId    openapi_types.UUID `json:"problem_id"`
	TopReached   bool               `json:"top_reached"`
	ZoneAttempts *int               `json:"zone_attempts,omitempty"`
	ZoneReached  bool               `json:"zone_reached"`
}

// CategoryCreate defines model for CategoryCreate.
type CategoryCreate struct {
	Name  string                  `json:"name"`
	Rules *map[string]interface{} `json:"rules,omitempty"`

	// SortOrder Defaults to 0 if omitted.
	SortOrder *int `json:"sort_order,omitempty"`
}

// Competition defines model for Competition.
type Competition struct {
	// Aggregation How per-event scores combine into a comp-level standing. Stored
	// as freeform jsonb in the DB; this is the canonical decoded form.
	// Method-specific fields (`drop`, `weights`, `finals_event_id`,
	// `best_n`) are only meaningful for some methods.
	Aggregation Aggregation `json:"aggregation"`
	CreatedAt   time.Time   `json:"created_at"`
	EndsAt      time.Time   `json:"ends_at"`

	// Format Comp shape. `single` = one event, `series` = multiple events
	// whose results combine per `aggregation`.
	Format CompetitionFormat  `json:"format"`
	Id     openapi_types.UUID `json:"id"`

	// LeaderboardVisibility Who can see the leaderboard:
	// - `public` — anyone (default; matches LEF/Mosaic league plan)
	// - `members` — anyone with org membership at the comp's location
	// - `registrants` — only climbers registered for this comp
	LeaderboardVisibility LeaderboardVisibility `json:"leaderboard_visibility"`
	LocationId            openapi_types.UUID    `json:"location_id"`
	Name                  string                `json:"name"`
	RegistrationClosesAt  *time.Time            `json:"registration_closes_at,omitempty"`
	RegistrationOpensAt   *time.Time            `json:"registration_opens_at,omitempty"`

	// ScoringConfig Scorer-specific config (shape depends on `scoring_rule`).
	ScoringConfig map[string]interface{} `json:"scoring_config"`

	// ScoringRule Name of the scorer to apply. Built-ins: `top_zone`, `fixed`,
	// `decay`. Per-event overrides live on `competition_events`.
	ScoringRule string `json:"scoring_rule"`

	// Slug URL-safe identifier, unique per location.
	Slug      string            `json:"slug"`
	StartsAt  time.Time         `json:"starts_at"`
	Status    CompetitionStatus `json:"status"`
	UpdatedAt time.Time         `json:"updated_at"`
}

// CompetitionCategory defines model for CompetitionCategory.
type CompetitionCategory struct {
	CompetitionId openapi_types.UUID `json:"competition_id"`
	Id            openapi_types.UUID `json:"id"`
	Name          string             `json:"name"`

	// Rules Freeform jsonb describing eligibility (age band, gender, etc.).
	// Shape is intentionally open — staff define what makes sense
	// per comp.
	Rules     map[string]interface{} `json:"rules"`
	SortOrder int                    `json:"sort_order"`
}

// CompetitionCreate defines model for CompetitionCreate.
type CompetitionCreate struct {
	// Aggregation How per-event scores combine into a comp-level standing. Stored
	// as freeform jsonb in the DB; this is the canonical decoded form.
	// Method-specific fields (`drop`, `weights`, `finals_event_id`,
	// `best_n`) are only meaningful for some methods.
	Aggregation *Aggregation `json:"aggregation,omitempty"`
	EndsAt      time.Time    `json:"ends_at"`

	// Format Comp shape. `single` = one event, `series` = multiple events
	// whose results combine per `aggregation`.
	Format CompetitionFormat `json:"format"`

	// LeaderboardVisibility Defaults to `public` if omitted.
	LeaderboardVisibility *LeaderboardVisibility  `json:"leaderboard_visibility,omitempty"`
	Name                  string                  `json:"name"`
	RegistrationClosesAt  *time.Time              `json:"registration_closes_at,omitempty"`
	RegistrationOpensAt   *time.Time              `json:"registration_opens_at,omitempty"`
	ScoringConfig         *map[string]interface{} `json:"scoring_config,omitempty"`
	ScoringRule           string                  `json:"scoring_rule"`

	// Slug Lowercase, digits, and hyphens; must start with alphanumeric.
	Slug     string    `json:"slug"`
	StartsAt time.Time `json:"starts_at"`

	// Status Defaults to `draft` if omitted.
	Status *CompetitionStatus `json:"status,omitempty"`
}

// CompetitionEvent defines model for CompetitionEvent.
type CompetitionEvent struct {
	CompetitionId         openapi_types.UUID      `json:"competition_id"`
	EndsAt                time.Time               `json:"ends_at"`
	Id                    openapi_types.UUID      `json:"id"`
	Name                  string                  `json:"name"`
	ScoringConfigOverride *map[string]interface{} `json:"scoring_config_override,omitempty"`

	// ScoringRuleOverride If set, overrides the comp-level scoring_rule for this event.
	// NULL means "use the comp default". Lets a series mix event types
	// (boulder + speed + lead under one comp).
	ScoringRuleOverride *string `json:"scoring_rule_override,omitempty"`

	// Sequence Position within the comp; unique per comp.
	Sequence int       `json:"sequence"`
	StartsAt time.Time `json:"starts_at"`

	// Weight Multiplier when aggregating event scores into a series total.
	Weight float32 `json:"weight"`
}

// CompetitionFormat Comp shape. `single` = one event, `series` = multiple events
// whose results combine per `aggregation`.
type CompetitionFormat string

// CompetitionProblem defines model for CompetitionProblem.
type CompetitionProblem struct {
	Color   *string            `json:"color,omitempty"`
	EventId openapi_types.UUID `json:"event_id"`
	Grade   *string            `json:"grade,omitempty"`
	Id      openapi_types.UUID `json:"id"`

	// Label Short identifier shown to climbers (e.g. "M1", "B7").
	Label string `json:"label"`

	// Points Used by `fixed` scorer; ignored by `top_zone` and `decay`.
	Points *float32 `json:"points,omitempty"`

	// RouteId Optional link to a routes table row (gym inventory).
	RouteId    *openapi_types.UUID `json:"route_id,omitempty"`
	SortOrder  int                 `json:"sort_order"`
	ZonePoints *float32            `json:"zone_points,omitempty"`
}

// CompetitionRegistration defines model for CompetitionRegistration.
type CompetitionRegistration struct {
	BibNumber     *int               `json:"bib_number,omitempty"`
	CategoryId    openapi_types.UUID `json:"category_id"`
	CompetitionId openapi_types.UUID `json:"competition_id"`
	CreatedAt     time.Time          `json:"created_at"`

	// DisplayName Snapshot at registration time.
	DisplayName    string             `json:"display_name"`
	Id             openapi_types.UUID `json:"id"`
	PaidAt         *time.Time         `json:"paid_at,omitempty"`
	UserId         openapi_types.UUID `json:"user_id"`
	WaiverSignedAt *time.Time         `json:"waiver_signed_at,omitempty"`
	WithdrawnAt    *time.Time         `json:"withdrawn_at,omitempty"`
}

// CompetitionStatus defines model for CompetitionStatus.
type CompetitionStatus string

// CompetitionUpdate All fields optional. Only fields present in the request are
// updated. To clear a nullable field, send explicit null.
type CompetitionUpdate struct {
	// Aggregation How per-event scores combine into a comp-level standing. Stored
	// as freeform jsonb in the DB; this is the canonical decoded form.
	// Method-specific fields (`drop`, `weights`, `finals_event_id`,
	// `best_n`) are only meaningful for some methods.
	Aggregation *Aggregation `json:"aggregation,omitempty"`
	EndsAt      *time.Time   `json:"ends_at,omitempty"`

	// Format Comp shape. `single` = one event, `series` = multiple events
	// whose results combine per `aggregation`.
	Format *CompetitionFormat `json:"format,omitempty"`

	// LeaderboardVisibility Who can see the leaderboard:
	// - `public` — anyone (default; matches LEF/Mosaic league plan)
	// - `members` — anyone with org membership at the comp's location
	// - `registrants` — only climbers registered for this comp
	LeaderboardVisibility *LeaderboardVisibility  `json:"leaderboard_visibility,omitempty"`
	Name                  *string                 `json:"name,omitempty"`
	RegistrationClosesAt  *time.Time              `json:"registration_closes_at,omitempty"`
	RegistrationOpensAt   *time.Time              `json:"registration_opens_at,omitempty"`
	ScoringConfig         *map[string]interface{} `json:"scoring_config,omitempty"`
	ScoringRule           *string                 `json:"scoring_rule,omitempty"`
	Slug                  *string                 `json:"slug,omitempty"`
	StartsAt              *time.Time              `json:"starts_at,omitempty"`
	Status                *CompetitionStatus      `json:"status,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Error Human-readable error message. Matches the existing routewerk envelope.
	Error string `json:"error"`
}

// EventCreate defines model for EventCreate.
type EventCreate struct {
	EndsAt                time.Time               `json:"ends_at"`
	Name                  string                  `json:"name"`
	ScoringConfigOverride *map[string]interface{} `json:"scoring_config_override,omitempty"`
	ScoringRuleOverride   *string                 `json:"scoring_rule_override,omitempty"`
	Sequence              int                     `json:"sequence"`
	StartsAt              time.Time               `json:"starts_at"`

	// Weight Defaults to 1.0 if omitted.
	Weight *float32 `json:"weight,omitempty"`
}

// EventUpdate All fields optional; only provided fields are updated.
type EventUpdate struct {
	EndsAt                *time.Time              `json:"ends_at,omitempty"`
	Name                  *string                 `json:"name,omitempty"`
	ScoringConfigOverride *map[string]interface{} `json:"scoring_config_override,omitempty"`
	ScoringRuleOverride   *string                 `json:"scoring_rule_override,omitempty"`
	Sequence              *int                    `json:"sequence,omitempty"`
	StartsAt              *time.Time              `json:"starts_at,omitempty"`
	Weight                *float32                `json:"weight,omitempty"`
}

// LeaderboardVisibility Who can see the leaderboard:
// - `public` — anyone (default; matches LEF/Mosaic league plan)
// - `members` — anyone with org membership at the comp's location
// - `registrants` — only climbers registered for this comp
type LeaderboardVisibility string

// MagicLinkRequest defines model for MagicLinkRequest.
type MagicLinkRequest struct {
	// Email The address to receive the sign-in link.
	Email openapi_types.Email `json:"email"`

	// Next Optional path to redirect to after successful verification.
	// Must be a relative path (no scheme, no host) — server validates
	// via `safeRedirect` and falls back to `/dashboard` if invalid.
	Next *string `json:"next,omitempty"`
}

// ProblemCreate defines model for ProblemCreate.
type ProblemCreate struct {
	Color      *string             `json:"color,omitempty"`
	Grade      *string             `json:"grade,omitempty"`
	Label      string              `json:"label"`
	Points     *float32            `json:"points,omitempty"`
	RouteId    *openapi_types.UUID `json:"route_id,omitempty"`
	SortOrder  *int                `json:"sort_order,omitempty"`
	ZonePoints *float32            `json:"zone_points,omitempty"`
}

// ProblemUpdate All fields optional; only provided fields are updated.
type ProblemUpdate struct {
	Color      *string             `json:"color,omitempty"`
	Grade      *string             `json:"grade,omitempty"`
	Label      *string             `json:"label,omitempty"`
	Points     *float32            `json:"points,omitempty"`
	RouteId    *openapi_types.UUID `json:"route_id,omitempty"`
	SortOrder  *int                `json:"sort_order,omitempty"`
	ZonePoints *float32            `json:"zone_points,omitempty"`
}

// RegistrationCreate defines model for RegistrationCreate.
type RegistrationCreate struct {
	// BibNumber Staff-assigned bib. Climbers self-registering should leave null.
	BibNumber  *int               `json:"bib_number,omitempty"`
	CategoryId openapi_types.UUID `json:"category_id"`

	// DisplayName Optional. Defaults to the user's display_name.
	DisplayName *string `json:"display_name,omitempty"`

	// UserId Optional. Defaults to the calling user. Setting a different
	// user_id requires `gym_manager+` role at the comp's location.
	UserId *openapi_types.UUID `json:"user_id,omitempty"`
}

// CompetitionId defines model for CompetitionId.
type CompetitionId = openapi_types.UUID

// EventId defines model for EventId.
type EventId = openapi_types.UUID

// LocationId defines model for LocationId.
type LocationId = openapi_types.UUID

// ProblemId defines model for ProblemId.
type ProblemId = openapi_types.UUID

// RegistrationId defines model for RegistrationId.
type RegistrationId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// cookieAuthContextKey is the context key for cookieAuth security scheme
type cookieAuthContextKey string

// ListCompetitionsParams defines parameters for ListCompetitions.
type ListCompetitionsParams struct {
	// Status Filter by status (e.g. `live`, `open`). Omit to include all statuses.
	Status *CompetitionStatus `form:"status,omitempty" json:"status,omitempty"`
}

// RequestMagicLinkJSONRequestBody defines body for RequestMagicLink for application/json ContentType.
type RequestMagicLinkJSONRequestBody = MagicLinkRequest

// UpdateCompetitionJSONRequestBody defines body for UpdateCompetition for application/json ContentType.
type UpdateCompetitionJSONRequestBody = CompetitionUpdate

// SubmitActionsJSONRequestBody defines body for SubmitActions for application/json ContentType.
type SubmitActionsJSONRequestBody = ActionsRequest

// CreateCategoryJSONRequestBody defines body for CreateCategory for application/json ContentType.
type CreateCategoryJSONRequestBody = CategoryCreate

// CreateEventJSONRequestBody defines body for CreateEvent for application/json ContentType.
type CreateEventJSONRequestBody = EventCreate

// CreateRegistrationJSONRequestBody defines body for CreateRegistration for application/json ContentType.
type CreateRegistrationJSONRequestBody = RegistrationCreate

// UpdateEventJSONRequestBody defines body for UpdateEvent for application/json ContentType.
type UpdateEventJSONRequestBody = EventUpdate

// CreateProblemJSONRequestBody defines body for CreateProblem for application/json ContentType.
type CreateProblemJSONRequestBody = ProblemCreate

// CreateCompetitionJSONRequestBody defines body for CreateCompetition for application/json ContentType.
type CreateCompetitionJSONRequestBody = CompetitionCreate

// UpdateProblemJSONRequestBody defines body for UpdateProblem for application/json ContentType.
type UpdateProblemJSONRequestBody = ProblemUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Request a magic-link sign-in email
	// (POST /auth/magic/request)
	RequestMagicLink(w http.ResponseWriter, r *http.Request)
	// Get a competition by id
	// (GET /competitions/{id})
	GetCompetition(w http.ResponseWriter, r *http.Request, id CompetitionId)
	// Update a competition
	// (PATCH /competitions/{id})
	UpdateCompetition(w http.ResponseWriter, r *http.Request, id CompetitionId)
	// Submit one or more attempt actions
	// (POST /competitions/{id}/actions)
	SubmitActions(w http.ResponseWriter, r *http.Request, id CompetitionId)
	// List categories under a competition (sort order ASC)
	// (GET /competitions/{id}/categories)
	ListCategories(w http.ResponseWriter, r *http.Request, id CompetitionId)
	// Create a category
	// (POST /competitions/{id}/categories)
	CreateCategory(w http.ResponseWriter, r *http.Request, id CompetitionId)
	// List events under a competition (sequence ASC)
	// (GET /competitions/{id}/events)
	ListEvents(w http.ResponseWriter, r *http.Request, id CompetitionId)
	// Create an event under a competition
	// (POST /competitions/{id}/events)
	CreateEvent(w http.ResponseWriter, r *http.Request, id CompetitionId)
	// List registrations for a competition
	// (GET /competitions/{id}/registrations)
	ListRegistrations(w http.ResponseWriter, r *http.Request, id CompetitionId)
	// Register self (or another climber, if staff) for a competition
	// (POST /competitions/{id}/registrations)
	CreateRegistration(w http.ResponseWriter, r *http.Request, id CompetitionId)
	// Update an event
	// (PATCH /events/{id})
	UpdateEvent(w http.ResponseWriter, r *http.Request, id EventId)
	// List problems under an event (sort order ASC)
	// (GET /events/{id}/problems)
	ListProblems(w http.ResponseWriter, r *http.Request, id EventId)
	// Create a problem under an event
	// (POST /events/{id}/problems)
	CreateProblem(w http.ResponseWriter, r *http.Request, id EventId)
	// List competitions at a location
	// (GET /locations/{locationId}/competitions)
	ListCompetitions(w http.ResponseWriter, r *http.Request, locationId LocationId, params ListCompetitionsParams)
	// Create a competition
	// (POST /locations/{locationId}/competitions)
	CreateCompetition(w http.ResponseWriter, r *http.Request, locationId LocationId)
	// Update a problem
	// (PATCH /problems/{id})
	UpdateProblem(w http.ResponseWriter, r *http.Request, id ProblemId)
	// Withdraw a registration (mark withdrawn)
	// (DELETE /registrations/{id})
	WithdrawRegistration(w http.ResponseWriter, r *http.Request, id RegistrationId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Request a magic-link sign-in email
// (POST /auth/magic/request)
func (_ Unimplemented) RequestMagicLink(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a competition by id
// (GET /competitions/{id})
func (_ Unimplemented) GetCompetition(w http.ResponseWriter, r *http.Request, id CompetitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a competition
// (PATCH /competitions/{id})
func (_ Unimplemented) UpdateCompetition(w http.ResponseWriter, r *http.Request, id CompetitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Submit one or more attempt actions
// (POST /competitions/{id}/actions)
func (_ Unimplemented) SubmitActions(w http.ResponseWriter, r *http.Request, id CompetitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List categories under a competition (sort order ASC)
// (GET /competitions/{id}/categories)
func (_ Unimplemented) ListCategories(w http.ResponseWriter, r *http.Request, id CompetitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a category
// (POST /competitions/{id}/categories)
func (_ Unimplemented) CreateCategory(w http.ResponseWriter, r *http.Request, id CompetitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List events under a competition (sequence ASC)
// (GET /competitions/{id}/events)
func (_ Unimplemented) ListEvents(w http.ResponseWriter, r *http.Request, id CompetitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an event under a competition
// (POST /competitions/{id}/events)
func (_ Unimplemented) CreateEvent(w http.ResponseWriter, r *http.Request, id CompetitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List registrations for a competition
// (GET /competitions/{id}/registrations)
func (_ Unimplemented) ListRegistrations(w http.ResponseWriter, r *http.Request, id CompetitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register self (or another climber, if staff) for a competition
// (POST /competitions/{id}/registrations)
func (_ Unimplemented) CreateRegistration(w http.ResponseWriter, r *http.Request, id CompetitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an event
// (PATCH /events/{id})
func (_ Unimplemented) UpdateEvent(w http.ResponseWriter, r *http.Request, id EventId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List problems under an event (sort order ASC)
// (GET /events/{id}/problems)
func (_ Unimplemented) ListProblems(w http.ResponseWriter, r *http.Request, id EventId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a problem under an event
// (POST /events/{id}/problems)
func (_ Unimplemented) CreateProblem(w http.ResponseWriter, r *http.Request, id EventId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List competitions at a location
// (GET /locations/{locationId}/competitions)
func (_ Unimplemented) ListCompetitions(w http.ResponseWriter, r *http.Request, locationId LocationId, params ListCompetitionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a competition
// (POST /locations/{locationId}/competitions)
func (_ Unimplemented) CreateCompetition(w http.ResponseWriter, r *http.Request, locationId LocationId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a problem
// (PATCH /problems/{id})
func (_ Unimplemented) UpdateProblem(w http.ResponseWriter, r *http.Request, id ProblemId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Withdraw a registration (mark withdrawn)
// (DELETE /registrations/{id})
func (_ Unimplemented) WithdrawRegistration(w http.ResponseWriter, r *http.Request, id RegistrationId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RequestMagicLink operation middleware
func (siw *ServerInterfaceWrapper) RequestMagicLink(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestMagicLink(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCompetition operation middleware
func (siw *ServerInterfaceWrapper) GetCompetition(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCompetition(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCompetition operation middleware
func (siw *ServerInterfaceWrapper) UpdateCompetition(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCompetition(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitActions operation middleware
func (siw *ServerInterfaceWrapper) SubmitActions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitActions(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCategories operation middleware
func (siw *ServerInterfaceWrapper) ListCategories(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCategories(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCategory operation middleware
func (siw *ServerInterfaceWrapper) CreateCategory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCategory(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEvents operation middleware
func (siw *ServerInterfaceWrapper) ListEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEvents(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEvent operation middleware
func (siw *ServerInterfaceWrapper) CreateEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRegistrations operation middleware
func (siw *ServerInterfaceWrapper) ListRegistrations(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRegistrations(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRegistration operation middleware
func (siw *ServerInterfaceWrapper) CreateRegistration(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRegistration(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateEvent operation middleware
func (siw *ServerInterfaceWrapper) UpdateEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id EventId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProblems operation middleware
func (siw *ServerInterfaceWrapper) ListProblems(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id EventId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProblems(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProblem operation middleware
func (siw *ServerInterfaceWrapper) CreateProblem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id EventId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProblem(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCompetitions operation middleware
func (siw *ServerInterfaceWrapper) ListCompetitions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "locationId" -------------
	var locationId LocationId

	err = runtime.BindStyledParameterWithOptions("simple", "locationId", chi.URLParam(r, "locationId"), &locationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCompetitionsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCompetitions(w, r, locationId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCompetition operation middleware
func (siw *ServerInterfaceWrapper) CreateCompetition(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "locationId" -------------
	var locationId LocationId

	err = runtime.BindStyledParameterWithOptions("simple", "locationId", chi.URLParam(r, "locationId"), &locationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCompetition(w, r, locationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProblem operation middleware
func (siw *ServerInterfaceWrapper) UpdateProblem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ProblemId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProblem(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WithdrawRegistration operation middleware
func (siw *ServerInterfaceWrapper) WithdrawRegistration(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id RegistrationId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WithdrawRegistration(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/magic/request", wrapper.RequestMagicLink)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/competitions/{id}", wrapper.GetCompetition)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/competitions/{id}", wrapper.UpdateCompetition)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/competitions/{id}/actions", wrapper.SubmitActions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/competitions/{id}/categories", wrapper.ListCategories)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/competitions/{id}/categories", wrapper.CreateCategory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/competitions/{id}/events", wrapper.ListEvents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/competitions/{id}/events", wrapper.CreateEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/competitions/{id}/registrations", wrapper.ListRegistrations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/competitions/{id}/registrations", wrapper.CreateRegistration)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/events/{id}", wrapper.UpdateEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events/{id}/problems", wrapper.ListProblems)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/events/{id}/problems", wrapper.CreateProblem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/locations/{locationId}/competitions", wrapper.ListCompetitions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/locations/{locationId}/competitions", wrapper.CreateCompetition)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/problems/{id}", wrapper.UpdateProblem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/registrations/{id}", wrapper.WithdrawRegistration)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H3rktvGsf+rdOGfKnHLvKxkJ/9kVak6siw7SqRItbs6/mDuIYdAg5jsYAaeGZCiVVuVT+cBTuUJ/SSn",
	"pmcAAiR4Wa1We2znk8UF5tbXX/d0wx+iWOWFkiitic4+RAXTLEeLmn49V3mBlluu5MvE/SFBE2teuD9E",
	"Z83H8O7dy2+GUT/i7kHBbBb1I8lyjM4inkT9SOOPJdeYRGdWl9iPTJxhztycqdI5s9FZVJb0pl0VbpSx",
	"mst5dHPTj14sUNpDG0D30r1u45WK2S5SVM/2bUCsx99tI2+1mgnMD1Gk8K/dK03Occ6N1ewYEdGNd+9x",
	"UzdusCmUNEhC/DVLzvHHEo11v2IlLUr6JysKwT1LRv8wbrsfGsv8TmManUX/b7RWkJF/akYvtFbaL9U+",
	"7msm3PYwAe2XhJlKVqA0cLlggifA9LzM3WTD6KYffav0jCcJyvvf2rPSZiitmxUTmJUWpLLAhFBLTMAq",
	"KFC7vYPNuAEWu2G0x78r+60qZXL/WzxHo0odI+0sdWvSBt5JVtpMaf4TfoZNvObGcDlv8izWmDjSMeG4",
	"dlMJI0nXszjGwvqN4XuWFwLdP9W1F9ybflRoVaC23Euje/ChktmZUgKZjLzMVgL/g3vpqhZsNfsHxtYR",
	"4hkx5Zk7s1+wPTVPMC+URRmvJte4OkJXaHPORkx4ctTrGgvBVtih6Je6ROBpU3oeGWhsCa5xBTmzcYYJ",
	"MCg0V7rSkuF6rZok/chYZvEQH59Zi3lhL+jdTTo2TldNt5uuLy3m20SNBUdpJ5bnaCzLi+2Tv6F/MPEU",
	"NMZKJw3tKg0mkCoN7s+Ohu6gNZETZnHgJu6idAcz28teWK3kXKxo1TxHmWDylMzq4iuYo0RNiu73PzA8",
	"wSFcoF6gHrtXywIdn2LuJJsJ0Gg1RwM9zzv4scQS4QtIBbtegUS7VPr6ZDiWzRN8IqnyfzjAZ9rWpXtz",
	"k8s0vLXobiafo/v9YNrDgo1CWeZu66W8lmopJ2GiqB8tHVcn8dptRv2IoM0kFsqgm1eqScaNVXrlpJpY",
	"OkEyZ1ddLnqnQoTt7CbWZeBLtVsuY43OeUX96CclSW5VEfWjUiaKJjRoOzZRzWcafrhNfC90ng8Wc3Oc",
	"NJDG3vSjnL1/6Uf9/rRenGnNVlsEqBbafWhzHsBDxy7XlvcWu6zs9c3m1tzO1tJ4ixlrIe6YsjaaGzis",
	"1NrhY3pMJgkXqFc1RrSqJMM8W3kLPnOGmvDZUdtqGeFDLAj0aBx/r3GezzXOmT/H5rH+opYOtww8+Dex",
	"0mggVvmMSwQurQLmfhYDgQsU7vQycWYYLqzSmIwlM5BqRAI+DkDMgEuwGcI3Xz/1lOCGfsdMKsljJiDB",
	"WCXerufDsXyNNlPJwBQY85THkHIUiYHeNNGqmPZhukQ+z6xx/0y5ZMJMvD7zZNofy+kMjZ3I6QkwjaCk",
	"WEGOTHI5T0tBjDIqR8hpFePtb1sq/QTbtPlWaahmP4NrxMIfKGdyBVYVW4Rz7M655LnT9sc1K7i0OEft",
	"eOGOtGMhU+YT93gip6P1qrLMZ6hBpSDU0odoxmHNhJuY6eTwihsU27G4JzEmE//69AyWGY+zEBMGDvpn",
	"w2P8l6d20/SZ0hnn9SGdpW4vGvUrTnQZwCAER+/fxeFCoHDECjxytlPG2FLK/cTbUsNt5Woq7ra9809N",
	"A7E2Zr+tk1fFRCNzVqYLAXuPMmkuKUsh2MzhaR8Cbm+BhuyZdJ/3q1famKa90y6L9JxZnCu9eq6xk2w+",
	"jP3Q4f9LEQibJNyDxreNka1TrpczStsJAcht6fkGU1YKr1OnDn6rnFuLSQNQ1+TaIAbtsvN4DeyxLRJt",
	"a7zXKTRevelHMVErmTDbEpe9IBhlYm41oHpr/84aJ/zWDyDAfZQYC2QJ6pliOpksuOEzLrhdHVrx1XrU",
	"f64HuelCTuhYLdotW43kioeKeym3Q7d2zKcKlHebznkYTsBWpnx+SAc2Ih3nnfTaw/o5oGcyViAkWDgx",
	"ASVhWq3iFG160lCChjY1XtnWp7+zHJ23cv6CnKJ2muUQy2oIX5dc2AGX5gymzkY4s+G9+nv0vjzBmK2m",
	"Q3hbe1a1QK15ggYEXyBtsoHtvV8zU+/Wt4kmyvn2Ht+dvxoYliJQ6MZTjroPpeQ/luhcOlQiNeyc0jJt",
	"b6dTDpqV5hY6deEH3PSjskhuqfMbRoqUoKkjQQMCbWqF77cM0waXt6SvPtNOdW4Sam2GWkasdboDdrTy",
	"GB3phYYwHGkC7mwpjvFCGyClDZH9wxmXc0DB54Fo0GNzhBmTSR/mKBMnlmjj4clwLC9IVR2aptQdLSpW",
	"4OwK/PzPfzlgnqaQYOpw+zJjFnJ2jQYMSoNj6cTaUaqlJ7s85AG/R9TaIPtaqtYzVYQ6xNodIODjHeXn",
	"dHq7vRkT4k0anf3wUX7tqr8Hp0yLciZ4PG3Bld+MazvokI70Aq/UEnXMDPYh4XNuTR+YTCBbFRlK8xTy",
	"0lC0ry0suc2AiSJjssxR89h5hsLhX+1m+q8f2OCn08GfrsJ/B1cfTvt/+PLmd5/cfxwnUx2eZL88JZql",
	"dkOcusDuttPYdBMdNv+A+tPV5Ccx67dW+7v6gbbcTiqkckiAd+hDt0C3Zm2z8GUKBm2/gZAozdJI1jTm",
	"oUQIZS8IMQ3H8u/vXr2iTImBcVQarEc7L+JkYxwN4RVaAwwMUmo75+9DLO32bMayN1OlSFDDF2AKxAS+",
	"AGcQoXTOC5T0E4ak92E7EAL07aO+VcbfgDpNDPklN/PTJmwj/3YwH/IR+ueTC9u7el0KywvBUcMyQwm1",
	"x3JuvZlPC3m0QEWrLBMNbOlTPLd0sxWpduGssOcDyvdt7fi2L52BooMhTA2Xc4FT+DMxlA7Wh6k/jPtr",
	"7skQHpmxXGbKIGg0ZGCqZKJj0bTh1ANmr/NDtIrPx/MWalgzorHzcIPfZTiE0nuSHw170UiJHTQCc828",
	"Dh6c9tgwmM1QdFxKZUrbRmACJlNL6ax0LLiTEwM9HM6HMI5ePx5HfRhHX///cXTSGasUisuulNk74xPV",
	"IfAKgdpT4HOpdHhUx2fkFavAbLcaV1Lcj7QqLXamGquLPhBcXlNcCPSyAetmBK2W0JuvcuDS8Ubp1UlX",
	"tvGwIdkLZ0O6ak2cAyfq0stadipGthY9oHXNko9tAZ7x2SQsfVQKLw6h0bGS/BGe9WMyTwk3hWCrSeU9",
	"N8RcssJkygKz7aoWN93wDs66YDy5ExgtDepj6bJkfIF6Yvhc4t1WdX4t0Wwp7zDLUf6jKS3rw26wq8Xx",
	"A8J8UYPTypITmoz6kQsMnH7wBc1YXb4yHWd80coMd1r4d5Qc2BadZ0JUV0Qq2JMhvJFiVf210Gjo1sLj",
	"hKqOiGkcy5BxGMKlM6jINDCoyOrH913InAC+LwSPuaWnXZdGv/Tw9KOSrf+OMPdHmA8RE94yEuy6xPKl",
	"XO36K18Pcda0IOuqsmirKgurKTaul8ucyYFGlpCG0VuQozFsjkN4TcVMPm7B99wQciZEsER9DSgXKFTR",
	"5Q82bN1m8UbjaM5R70ox3VoTP3UoeHzotzdY+mwRTzNr8Hi4475sB246LnLZycNbuIOnvgqg0GrBqc7A",
	"P2YaobL/W+b8wUXh47MCt4qr71FUttm/dYZux7LF0+8zBTGTYNBnJRpe7GwsB+sE6M///BcwuXJxaS9k",
	"LZ6GEkkDr158O3qtDOOxm2BeIhSCyROaIEeKpVozUJZP6TmEhxkvHDytcg2PTH0xRFNULkraMA0JXR2l",
	"+ceoQ/0ipV7cNK2g158j6kdhyWjt+Vxs0oWQXrM5j19xed0oBWua7Zxx4cy238d/hEfDWOXOUeJ7x1By",
	"FSNPlMGT0yd/6LDnfp6tItUMgSWJRkM2QGOMfOGZ5FDwgEuK7VpRm5+KisxeoZzbLDp78vuvulSKdrcz",
	"aCyYzfyiCdcYWwogU+ti5DKO0Zi0FLBAzdNQ0Dwcy9elsTBDF2iiYNbtlabpSQXkJLEPUkGmjD3x9yhU",
	"DQhUtswsmrFccAZTw1I8D+v6iDhlQhiYsZgC2ekoYSYjCaU8aih8DimOij0dhD/o2Yh4XVYxZEB2+bbj",
	"8yDHpzbqnMWeTMOt0gP/tyJ7f7w9tL5nH/Rvlh3Fsi3uNPMpu9ShnVXZLARnaTpgxsfxMOOzITyv7LhB",
	"kQ4qY+7wqclUKRLnUhboo8PdVLhDmmZ//uRNHfk2IZkzwy6kf2SgObwzn9LIcxw7dcyEcBRwQ4dwgZbw",
	"OoOEpylqlHYsw6wQ1MrAdL7KJzmTbI76iyloJXCHUz2qMn5DY5tE3dZbgj5xqbldXZCtD9WeTKN+Vjo/",
	"VP2q8uDRX7+/jPodBYa5mnGBMIJnb1+GjgAzhDczy7gE8hBv31xcwogVfLR4PGKlzUZCzbmcjmVPoy21",
	"NDBl5KYmVl2jnMIXDkOkGk0W/nIyhL8Q0jkby+mz0LFDtDmDr2mfMC5PT7+M/7G09A8MOXTvyaKzcJo1",
	"2TJrC5/zU9ccqzNvH2+m1dKghhFcvH22Pt8FWmClVTmzPKZ6A+9vWcPjjmXBjFkqnQAdGHqBFP74J+Co",
	"5zDLgJK+5J9XY9mbfvfiEkb+54BeoPNbW1Au5wu4YDlecIt/fsXeu5+Okwg9Tm15SbhTouY3f7p1+9tE",
	"LycGjfGVLFUNZ8H/hivfr8RlqrYJcf7i4pL46/DaeRWFPvKwrQqBrWbxNYm9TMCURaG0v++Ribdhw7G8",
	"bFQ9h34slYLVpc1o7plyQCZD+E5VeKM3daZCSyZIhKb9gDsUK/ggVgnOkSqcZUIDLxYoLP6N28Ar6E2X",
	"OBuZgo2MjkeCzzamKVC6mejajo7siH1eSpjm7BrBPXMreHhV9b54bo+lKTCGOGNyjuYpPH8JKePC+F4l",
	"UmMfAjZ6ZlIu0ECieWqHYzmWbzNmEB4jFKoohcNVTZlw2kJHo9vH5+fvvgFmgAFd9aFMBlYNUCZjaQSP",
	"HdhkFvA96pibkDxISyGg4AUK7kIB2vDP//0/jsB0ZPpxebH+MZYk6EqaMif+nwwhbDJ1ANeE1GHOuHTs",
	"pZ3VPIaev+rqj2WoiDX9Vhrb9L0tljzlmIRurnp8v4VS+2NZsbUR5ziJv3gBxmpkeRB2yy2hyFo2nbRG",
	"/WiB2ngRPh0+Hp46hQ8Mj86iL4enwy99uUJG9s8bJyL/SDfaSZTpAN/fBZbSJTDd0A1Ks8b6ZLeIdYRT",
	"DXBbOYsQJQzH8plYspULiLwVfHL6hJC2J7DvFKHCpsQ3VwpYZmgz1M5ySEW+YixpfvfaOq7qg1HAJDBr",
	"WXyN2oWMjywg1WiQ+MaxKr1KjuUrtqJgjJ4InnNrzqiA/+Vb6NXJpyeno5xLL5H0EmrSOqqgGvhN9L6E",
	"ETz+PeRc9gFlqnSMSZVtdvrshJTNGZfGhk6IwEAHSOpG3ygEcHVAF3p20divVbL6ZH2aWwHjTduLhibL",
	"Vsfvk9Mnn2z9ur+zs1815ObDO9DzJKYUfMaKAqUh9+rirLlWpUx8X93JsOXeo7Mfrqi5IGd61Zy3aWYq",
	"oa3iUcvmhtppnFu8ctONGpbejD7w5MYdbo5EgTbzvkP7vNVitkG/009Gv+YyHSS8DEgqvEKFYF+dPt41",
	"a73NUaspmAZ9dXhQ3cpM1K/p/Z0DCi0/OVuBx2+ByE3KRld0Ubf+TsKOeqb1K6P2dxRursiexR1o5vwj",
	"gCes47expCai44O4Dr32UeKmdHx6xd6+KztKsz+bZPpNJR3SeXpY0BrfHPh4gf7y8KD19wPuqAL+tG0t",
	"2C3/ncZm1GjivLN6dLrzdwGQLDW3WOORkKDEKnn5yPiKEGowgxcszgKCGUsqQPYNAw52Os9ft/1an0zd",
	"7ohOtcqBjSV1Qg9CJzQUmZIOAbgwFQxLUayGEDpIScUKrVyMQb51LCmD8JSgZ+n0O1HO2bOZ0l6pfb+l",
	"8/R+Do/1fLq4brsN+d4kCbgB88JCb6VKcDtNvNf2GWJf++Jez5m+hp/8Zplvvg92JLSEVhMR2qDBVhWN",
	"sXQb3eO5v1EWK/qr8VPyNHxFQiNLVn7pUibKD9e4QF1DKt96OsNUaZ9yzZWxlIOV1gVfgNLqVUhOGwyn",
	"/Qm18r2qDk/P19noqnO1F9geiuvGEmCuWYyw5DJRy77DYVRefuKo+3Ld5X3m/TSjnnmYbvR/T6niK3wG",
	"Y7txPuCjVjNHIOREqPn0aSUaFW4kGBh7BvjaMs/tdpzswlTUvniXCqcIZa6RebUT8K2zzuAHkfNVaxVR",
	"ZiiUnFPqg1WfxvFvTMNV0RQyZnz064BL1YrrrxF8ZzhMm43n004UeFHOcm6D3N+Tp9hoHv/MbmKzK7zD",
	"VbxFPQhBUlU2WIiyCsLcHyjkDnq20YJdB2E7erDH8tfrdbz0UGEmZak01lRitUjdygeFlFpIm3Zi31fc",
	"2Ofr1+4oOkf1x3e1Am33527J1XqXD4OLHaVgTdFQF91Gyj3jXBi5N3h28fzkXkFzJyr4GMy8Zcd84r1m",
	"zj1B3nbj8FGG7PF94N21EO4UuhWEIrpfMej1fHACveb7rayNz6PttTQv/Cuf2cr4tpQjTIzfntdf73rW",
	"3xl4MJMTvhPRbW7C9h7c2GTIkolBaz/W2Hge3Y+ladaNPZyZCVK4Q+p+QwamguAdEn1bk9PK0zcsz8aV",
	"vlxRFnj9wb/S+BQzCG7sEC7b+frBurp2LFMuLGroLdkC4asTmKsFuhAmU0vIyziDBC3jAkrJ0pQLXs9v",
	"wCB2RQlOq89bG//M9rDVs3CEWWxt9gEtYYvbFDMcKTz3Zf++d+GhVDANV+XTquy8utgwXXftLvwey94G",
	"QOs2lyeQsxW4uBTYepmx9Hd7tAZ9Eom6uYTplDevdy2m34+d7ajdeDhz2xby/UL96zS+bsCf7v8ToaG6",
	"pkp77SyWXKeNb9rXO5UYo0ih55RaKroyDKmsPvA05Kxuo/POYXjoVF/+3M4IVN9ZPuqC4g74xyeb7x3/",
	"PPi1wk78U90t+GbmX/+tQsA/R4vuqKpL2Btava1e+sxgomrePQJHVFt8QAhRkbICnxUWvb/ETcuM3HcU",
	"9bb+cup92JF2lfLDufZa5HaK2G8pXVMlzNsSvd+6VHJkRh/W3+G/aQVY+zPGzRe3NGKjJtEHULMV+D63",
	"0PM+FXxBHwxThS+XfJP7giMuY1EmCEyIMMJ/jJPKA38skRJToTqw/nLVrWWobqG7+sz28hhDSaZKpU2g",
	"Y/ogcYnGQsq1scNfiJT6pHnjGM6gsdqOfToz2/jfUdwtOX4wK/45a0Ee3NR2Av5GBvKXYmc/Qxx0Icp5",
	"HQRx6aJ9L1O86bd35dyPDWkqAPORQc36f5byecKazwJIHjy02QNIquAm8O23UDS1/nz/Hjlu5fJqYU5Q",
	"YOcH2xuVIDPcKgR5ZHxG9805dGbVxnKrTPBCpRb8cusKZrV0iGMVcotlwq2v/Z7x2ViGr3dz/410n9zQ",
	"WHbn3L4P3wDZyrq1hPGr7pQifTzkl+Lhqw1TW2Yjpdajcqn6WyifMKLa+L8s3VxtVA+324J+uLrpf2g1",
	"zfxw5Wyfb9boAqyFVkkZB46VWoTeG3M2GtXfMximYjVMcBG5ydvDjWVzLue7xw4SXOwZ72RUgHvWnOFs",
	"RKBdZMrYsz+e/vGUDHig6Ifd/3cjxwpqb/E9NCB4ivEqFgi9qten7wurqdm3D3/9/hJCKxN9sCkgbSqs",
	"3t7spao+UFf3ewzBX6P2G8USfdjZW+E2V319HDIm56BSakYx2Fi+JTI3Vzf/GwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
