// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
	CookieAuthScopes cookieAuthContextKey = "cookieAuth.Scopes"
)

// Defines values for ActionRejectedReason.
const (
	EventClosed      ActionRejectedReason = "event_closed"
	NoHistory        ActionRejectedReason = "no_history"
	ServerError      ActionRejectedReason = "server_error"
	UnknownProblem   ActionRejectedReason = "unknown_problem"
	WrongCompetition ActionRejectedReason = "wrong_competition"
)

// Valid indicates whether the value is a known member of the ActionRejectedReason enum.
func (e ActionRejectedReason) Valid() bool {
	switch e {
	case EventClosed:
		return true
	case NoHistory:
		return true
	case ServerError:
		return true
	case UnknownProblem:
		return true
	case WrongCompetition:
		return true
	default:
		return false
	}
}

// Defines values for ActionType.
const (
	Increment ActionType = "increment"
	Reset     ActionType = "reset"
	Top       ActionType = "top"
	Undo      ActionType = "undo"
	Zone      ActionType = "zone"
)

// Valid indicates whether the value is a known member of the ActionType enum.
func (e ActionType) Valid() bool {
	switch e {
	case Increment:
		return true
	case Reset:
		return true
	case Top:
		return true
	case Undo:
		return true
	case Zone:
		return true
	default:
		return false
	}
}

// Defines values for AggregationMethod.
const (
	BestN          AggregationMethod = "best_n"
	Sum            AggregationMethod = "sum"
	SumDropN       AggregationMethod = "sum_drop_n"
	WeightedFinals AggregationMethod = "weighted_finals"
)

// Valid indicates whether the value is a known member of the AggregationMethod enum.
func (e AggregationMethod) Valid() bool {
	switch e {
	case BestN:
		return true
	case Sum:
		return true
	case SumDropN:
		return true
	case WeightedFinals:
		return true
	default:
		return false
	}
}

// Defines values for CompetitionFormat.
const (
	Series CompetitionFormat = "series"
	Single CompetitionFormat = "single"
)

// Valid indicates whether the value is a known member of the CompetitionFormat enum.
func (e CompetitionFormat) Valid() bool {
	switch e {
	case Series:
		return true
	case Single:
		return true
	default:
		return false
	}
}

// Defines values for CompetitionStatus.
const (
	Archived CompetitionStatus = "archived"
	Closed   CompetitionStatus = "closed"
	Draft    CompetitionStatus = "draft"
	Live     CompetitionStatus = "live"
	Open     CompetitionStatus = "open"
)

// Valid indicates whether the value is a known member of the CompetitionStatus enum.
func (e CompetitionStatus) Valid() bool {
	switch e {
	case Archived:
		return true
	case Closed:
		return true
	case Draft:
		return true
	case Live:
		return true
	case Open:
		return true
	default:
		return false
	}
}

// Defines values for LeaderboardVisibility.
const (
	Members     LeaderboardVisibility = "members"
	Public      LeaderboardVisibility = "public"
	Registrants LeaderboardVisibility = "registrants"
)

// Valid indicates whether the value is a known member of the LeaderboardVisibility enum.
func (e LeaderboardVisibility) Valid() bool {
	switch e {
	case Members:
		return true
	case Public:
		return true
	case Registrants:
		return true
	default:
		return false
	}
}

// Accepted defines model for Accepted.
type Accepted struct {
	Ok bool `json:"ok"`
}

// ActionApplied defines model for ActionApplied.
type ActionApplied struct {
	IdempotencyKey *openapi_types.UUID `json:"idempotency_key,omitempty"`
	ProblemId      openapi_types.UUID  `json:"problem_id"`

	// Replayed True if this action's idempotency key matched a prior request.
	Replayed *bool        `json:"replayed,omitempty"`
	State    AttemptState `json:"state"`
}

// ActionItem defines model for ActionItem.
type ActionItem struct {
	// ClientTimestamp Optional; recorded but not used for ordering.
	ClientTimestamp *time.Time `json:"client_timestamp,omitempty"`

	// IdempotencyKey Strongly recommended; UUIDv4 generated client-side. Server
	// dedupes accidental retries (action queue + flaky network).
	IdempotencyKey *openapi_types.UUID `json:"idempotency_key,omitempty"`
	ProblemId      openapi_types.UUID  `json:"problem_id"`
	Type           ActionType          `json:"type"`
}

// ActionRejected defines model for ActionRejected.
type ActionRejected struct {
	IdempotencyKey *openapi_types.UUID  `json:"idempotency_key,omitempty"`
	ProblemId      openapi_types.UUID   `json:"problem_id"`
	Reason         ActionRejectedReason `json:"reason"`
}

// ActionRejectedReason defines model for ActionRejected.Reason.
type ActionRejectedReason string

// ActionType defines model for ActionType.
type ActionType string

// ActionsRequest defines model for ActionsRequest.
type ActionsRequest struct {
	Actions []ActionItem `json:"actions"`
}

// ActionsResponse defines model for ActionsResponse.
type ActionsResponse struct {
	Applied  []ActionApplied  `json:"applied"`
	Rejected []ActionRejected `json:"rejected"`

	// State Current state for every problem touched by this batch.
	State []AttemptState `json:"state"`
}

// Aggregation How per-event scores combine into a comp-level standing. Stored
// as freeform jsonb in the DB; this is the canonical decoded form.
// Method-specific fields (`drop`, `weights`, `finals_event_id`,
// `best_n`) are only meaningful for some methods.
type Aggregation struct {
	// BestN For `best_n`: keep this many top per-event scores.
	BestN *int `json:"best_n,omitempty"`

	// Drop For `sum_drop_n`/`best_n`: number of low events to discard.
	Drop *int `json:"drop,omitempty"`

	// FinalsEventId For `weighted_finals`: which event is the finals.
	FinalsEventId *openapi_types.UUID `json:"finals_event_id,omitempty"`
	Method        *AggregationMethod  `json:"method,omitempty"`

	// Weights For `weighted_finals`: parallel to event sequence.
	Weights *[]int `json:"weights,omitempty"`
}

// AggregationMethod defines model for Aggregation.Method.
type AggregationMethod string

// AttemptOverride Body for POST /attempts/{id}/override. The fields here
// wholesale replace the attempt's state — staff is asserting
// "this attempt is now exactly this." A log entry is appended
// with action=override.
type AttemptOverride struct {
	Attempts     int     `json:"attempts"`
	Notes        *string `json:"notes,omitempty"`
	TopReached   bool    `json:"top_reached"`
	ZoneAttempts *int    `json:"zone_attempts,omitempty"`
	ZoneReached  bool    `json:"zone_reached"`
}

// AttemptState defines model for AttemptState.
type AttemptState struct {
	Attempts     int                `json:"attempts"`
	ProblemId    openapi_types.UUID `json:"problem_id"`
	TopReached   bool               `json:"top_reached"`
	ZoneAttempts *int               `json:"zone_attempts,omitempty"`
	ZoneReached  bool               `json:"zone_reached"`
}

// CategoryCreate defines model for CategoryCreate.
type CategoryCreate struct {
	Name  string                  `json:"name"`
	Rules *map[string]interface{} `json:"rules,omitempty"`

	// SortOrder Defaults to 0 if omitted.
	SortOrder *int `json:"sort_order,omitempty"`
}

// Competition defines model for Competition.
type Competition struct {
	// Aggregation How per-event scores combine into a comp-level standing. Stored
	// as freeform jsonb in the DB; this is the canonical decoded form.
	// Method-specific fields (`drop`, `weights`, `finals_event_id`,
	// `best_n`) are only meaningful for some methods.
	Aggregation Aggregation `json:"aggregation"`
	CreatedAt   time.Time   `json:"created_at"`
	EndsAt      time.Time   `json:"ends_at"`

	// Format Comp shape. `single` = one event, `series` = multiple events
	// whose results combine per `aggregation`.
	Format CompetitionFormat  `json:"format"`
	Id     openapi_types.UUID `json:"id"`

	// LeaderboardVisibility Who can see the leaderboard:
	// - `public` — anyone (default; matches LEF/Mosaic league plan)
	// - `members` — anyone with org membership at the comp's location
	// - `registrants` — only climbers registered for this comp
	LeaderboardVisibility LeaderboardVisibility `json:"leaderboard_visibility"`
	LocationId            openapi_types.UUID    `json:"location_id"`
	Name                  string                `json:"name"`
	RegistrationClosesAt  *time.Time            `json:"registration_closes_at,omitempty"`
	RegistrationOpensAt   *time.Time            `json:"registration_opens_at,omitempty"`

	// ScoringConfig Scorer-specific config (shape depends on `scoring_rule`).
	ScoringConfig map[string]interface{} `json:"scoring_config"`

	// ScoringRule Name of the scorer to apply. Built-ins: `top_zone`, `fixed`,
	// `decay`. Per-event overrides live on `competition_events`.
	ScoringRule string `json:"scoring_rule"`

	// Slug URL-safe identifier, unique per location.
	Slug      string            `json:"slug"`
	StartsAt  time.Time         `json:"starts_at"`
	Status    CompetitionStatus `json:"status"`
	UpdatedAt time.Time         `json:"updated_at"`
}

// CompetitionAttempt defines model for CompetitionAttempt.
type CompetitionAttempt struct {
	Attempts       int                 `json:"attempts"`
	Id             openapi_types.UUID  `json:"id"`
	LoggedAt       time.Time           `json:"logged_at"`
	Notes          *string             `json:"notes,omitempty"`
	ProblemId      openapi_types.UUID  `json:"problem_id"`
	RegistrationId openapi_types.UUID  `json:"registration_id"`
	TopReached     bool                `json:"top_reached"`
	UpdatedAt      time.Time           `json:"updated_at"`
	VerifiedAt     *time.Time          `json:"verified_at,omitempty"`
	VerifiedBy     *openapi_types.UUID `json:"verified_by,omitempty"`
	ZoneAttempts   *int                `json:"zone_attempts,omitempty"`
	ZoneReached    bool                `json:"zone_reached"`
}

// CompetitionCategory defines model for CompetitionCategory.
type CompetitionCategory struct {
	CompetitionId openapi_types.UUID `json:"competition_id"`
	Id            openapi_types.UUID `json:"id"`
	Name          string             `json:"name"`

	// Rules Freeform jsonb describing eligibility (age band, gender, etc.).
	// Shape is intentionally open — staff define what makes sense
	// per comp.
	Rules     map[string]interface{} `json:"rules"`
	SortOrder int                    `json:"sort_order"`
}

// CompetitionCreate defines model for CompetitionCreate.
type CompetitionCreate struct {
	// Aggregation How per-event scores combine into a comp-level standing. Stored
	// as freeform jsonb in the DB; this is the canonical decoded form.
	// Method-specific fields (`drop`, `weights`, `finals_event_id`,
	// `best_n`) are only meaningful for some methods.
	Aggregation *Aggregation `json:"aggregation,omitempty"`
	EndsAt      time.Time    `json:"ends_at"`

	// Format Comp shape. `single` = one event, `series` = multiple events
	// whose results combine per `aggregation`.
	Format CompetitionFormat `json:"format"`

	// LeaderboardVisibility Defaults to `public` if omitted.
	LeaderboardVisibility *LeaderboardVisibility  `json:"leaderboard_visibility,omitempty"`
	Name                  string                  `json:"name"`
	RegistrationClosesAt  *time.Time              `json:"registration_closes_at,omitempty"`
	RegistrationOpensAt   *time.Time              `json:"registration_opens_at,omitempty"`
	ScoringConfig         *map[string]interface{} `json:"scoring_config,omitempty"`
	ScoringRule           string                  `json:"scoring_rule"`

	// Slug Lowercase, digits, and hyphens; must start with alphanumeric.
	Slug     string    `json:"slug"`
	StartsAt time.Time `json:"starts_at"`

	// Status Defaults to `draft` if omitted.
	Status *CompetitionStatus `json:"status,omitempty"`
}

// CompetitionEvent defines model for CompetitionEvent.
type CompetitionEvent struct {
	CompetitionId         openapi_types.UUID      `json:"competition_id"`
	EndsAt                time.Time               `json:"ends_at"`
	Id                    openapi_types.UUID      `json:"id"`
	Name                  string                  `json:"name"`
	ScoringConfigOverride *map[string]interface{} `json:"scoring_config_override,omitempty"`

	// ScoringRuleOverride If set, overrides the comp-level scoring_rule for this event.
	// NULL means "use the comp default". Lets a series mix event types
	// (boulder + speed + lead under one comp).
	ScoringRuleOverride *string `json:"scoring_rule_override,omitempty"`

	// Sequence Position within the comp; unique per comp.
	Sequence int       `json:"sequence"`
	StartsAt time.Time `json:"starts_at"`

	// Weight Multiplier when aggregating event scores into a series total.
	Weight float32 `json:"weight"`
}

// CompetitionFormat Comp shape. `single` = one event, `series` = multiple events
// whose results combine per `aggregation`.
type CompetitionFormat string

// CompetitionProblem defines model for CompetitionProblem.
type CompetitionProblem struct {
	Color   *string            `json:"color,omitempty"`
	EventId openapi_types.UUID `json:"event_id"`
	Grade   *string            `json:"grade,omitempty"`
	Id      openapi_types.UUID `json:"id"`

	// Label Short identifier shown to climbers (e.g. "M1", "B7").
	Label string `json:"label"`

	// Points Used by `fixed` scorer; ignored by `top_zone` and `decay`.
	Points *float32 `json:"points,omitempty"`

	// RouteId Optional link to a routes table row (gym inventory).
	RouteId    *openapi_types.UUID `json:"route_id,omitempty"`
	SortOrder  int                 `json:"sort_order"`
	ZonePoints *float32            `json:"zone_points,omitempty"`
}

// CompetitionRegistration defines model for CompetitionRegistration.
type CompetitionRegistration struct {
	BibNumber     *int               `json:"bib_number,omitempty"`
	CategoryId    openapi_types.UUID `json:"category_id"`
	CompetitionId openapi_types.UUID `json:"competition_id"`
	CreatedAt     time.Time          `json:"created_at"`

	// DisplayName Snapshot at registration time.
	DisplayName    string             `json:"display_name"`
	Id             openapi_types.UUID `json:"id"`
	PaidAt         *time.Time         `json:"paid_at,omitempty"`
	UserId         openapi_types.UUID `json:"user_id"`
	WaiverSignedAt *time.Time         `json:"waiver_signed_at,omitempty"`
	WithdrawnAt    *time.Time         `json:"withdrawn_at,omitempty"`
}

// CompetitionStatus defines model for CompetitionStatus.
type CompetitionStatus string

// CompetitionUpdate All fields optional. Only fields present in the request are
// updated. To clear a nullable field, send explicit null.
type CompetitionUpdate struct {
	// Aggregation How per-event scores combine into a comp-level standing. Stored
	// as freeform jsonb in the DB; this is the canonical decoded form.
	// Method-specific fields (`drop`, `weights`, `finals_event_id`,
	// `best_n`) are only meaningful for some methods.
	Aggregation *Aggregation `json:"aggregation,omitempty"`
	EndsAt      *time.Time   `json:"ends_at,omitempty"`

	// Format Comp shape. `single` = one event, `series` = multiple events
	// whose results combine per `aggregation`.
	Format *CompetitionFormat `json:"format,omitempty"`

	// LeaderboardVisibility Who can see the leaderboard:
	// - `public` — anyone (default; matches LEF/Mosaic league plan)
	// - `members` — anyone with org membership at the comp's location
	// - `registrants` — only climbers registered for this comp
	LeaderboardVisibility *LeaderboardVisibility  `json:"leaderboard_visibility,omitempty"`
	Name                  *string                 `json:"name,omitempty"`
	RegistrationClosesAt  *time.Time              `json:"registration_closes_at,omitempty"`
	RegistrationOpensAt   *time.Time              `json:"registration_opens_at,omitempty"`
	ScoringConfig         *map[string]interface{} `json:"scoring_config,omitempty"`
	ScoringRule           *string                 `json:"scoring_rule,omitempty"`
	Slug                  *string                 `json:"slug,omitempty"`
	StartsAt              *time.Time              `json:"starts_at,omitempty"`
	Status                *CompetitionStatus      `json:"status,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Error Human-readable error message. Matches the existing routewerk envelope.
	Error string `json:"error"`
}

// EventCreate defines model for EventCreate.
type EventCreate struct {
	EndsAt                time.Time               `json:"ends_at"`
	Name                  string                  `json:"name"`
	ScoringConfigOverride *map[string]interface{} `json:"scoring_config_override,omitempty"`
	ScoringRuleOverride   *string                 `json:"scoring_rule_override,omitempty"`
	Sequence              int                     `json:"sequence"`
	StartsAt              time.Time               `json:"starts_at"`

	// Weight Defaults to 1.0 if omitted.
	Weight *float32 `json:"weight,omitempty"`
}

// EventUpdate All fields optional; only provided fields are updated.
type EventUpdate struct {
	EndsAt                *time.Time              `json:"ends_at,omitempty"`
	Name                  *string                 `json:"name,omitempty"`
	ScoringConfigOverride *map[string]interface{} `json:"scoring_config_override,omitempty"`
	ScoringRuleOverride   *string                 `json:"scoring_rule_override,omitempty"`
	Sequence              *int                    `json:"sequence,omitempty"`
	StartsAt              *time.Time              `json:"starts_at,omitempty"`
	Weight                *float32                `json:"weight,omitempty"`
}

// Leaderboard defines model for Leaderboard.
type Leaderboard struct {
	// CategoryId NULL when the leaderboard spans all categories.
	CategoryId    *openapi_types.UUID `json:"category_id,omitempty"`
	CompetitionId openapi_types.UUID  `json:"competition_id"`
	Entries       []LeaderboardEntry  `json:"entries"`
	GeneratedAt   time.Time           `json:"generated_at"`
	ScoringRule   string              `json:"scoring_rule"`
}

// LeaderboardEntry defines model for LeaderboardEntry.
type LeaderboardEntry struct {
	AttemptsToTop  int                 `json:"attempts_to_top"`
	AttemptsToZone int                 `json:"attempts_to_zone"`
	BibNumber      *int                `json:"bib_number,omitempty"`
	CategoryId     *openapi_types.UUID `json:"category_id,omitempty"`
	DisplayName    string              `json:"display_name"`

	// Points Aggregate score from the comp's scorer. Used by `fixed`
	// and `decay`; `top_zone` ranks on (tops, zones, attempts)
	// and leaves this at 0.
	Points float32 `json:"points"`

	// Rank 1-indexed; ties share the lower rank (1224 ranking).
	Rank           int                `json:"rank"`
	RegistrationId openapi_types.UUID `json:"registration_id"`
	Tops           int                `json:"tops"`
	Zones          int                `json:"zones"`
}

// LeaderboardVisibility Who can see the leaderboard:
// - `public` — anyone (default; matches LEF/Mosaic league plan)
// - `members` — anyone with org membership at the comp's location
// - `registrants` — only climbers registered for this comp
type LeaderboardVisibility string

// MagicLinkRequest defines model for MagicLinkRequest.
type MagicLinkRequest struct {
	// Email The address to receive the sign-in link.
	Email openapi_types.Email `json:"email"`

	// Next Optional path to redirect to after successful verification.
	// Must be a relative path (no scheme, no host) — server validates
	// via `safeRedirect` and falls back to `/dashboard` if invalid.
	Next *string `json:"next,omitempty"`
}

// ProblemCreate defines model for ProblemCreate.
type ProblemCreate struct {
	Color      *string             `json:"color,omitempty"`
	Grade      *string             `json:"grade,omitempty"`
	Label      string              `json:"label"`
	Points     *float32            `json:"points,omitempty"`
	RouteId    *openapi_types.UUID `json:"route_id,omitempty"`
	SortOrder  *int                `json:"sort_order,omitempty"`
	ZonePoints *float32            `json:"zone_points,omitempty"`
}

// ProblemUpdate All fields optional; only provided fields are updated.
type ProblemUpdate struct {
	Color      *string             `json:"color,omitempty"`
	Grade      *string             `json:"grade,omitempty"`
	Label      *string             `json:"label,omitempty"`
	Points     *float32            `json:"points,omitempty"`
	RouteId    *openapi_types.UUID `json:"route_id,omitempty"`
	SortOrder  *int                `json:"sort_order,omitempty"`
	ZonePoints *float32            `json:"zone_points,omitempty"`
}

// RegistrationCreate defines model for RegistrationCreate.
type RegistrationCreate struct {
	// BibNumber Staff-assigned bib. Climbers self-registering should leave null.
	BibNumber  *int               `json:"bib_number,omitempty"`
	CategoryId openapi_types.UUID `json:"category_id"`

	// DisplayName Optional. Defaults to the user's display_name.
	DisplayName *string `json:"display_name,omitempty"`

	// UserId Optional. Defaults to the calling user. Setting a different
	// user_id requires `gym_manager+` role at the comp's location.
	UserId *openapi_types.UUID `json:"user_id,omitempty"`
}

// AttemptId defines model for AttemptId.
type AttemptId = openapi_types.UUID

// CompetitionId defines model for CompetitionId.
type CompetitionId = openapi_types.UUID

// EventId defines model for EventId.
type EventId = openapi_types.UUID

// LocationId defines model for LocationId.
type LocationId = openapi_types.UUID

// ProblemId defines model for ProblemId.
type ProblemId = openapi_types.UUID

// RegistrationId defines model for RegistrationId.
type RegistrationId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// cookieAuthContextKey is the context key for cookieAuth security scheme
type cookieAuthContextKey string

// GetLeaderboardParams defines parameters for GetLeaderboard.
type GetLeaderboardParams struct {
	// Category Optional category UUID to filter rankings.
	Category *openapi_types.UUID `form:"category,omitempty" json:"category,omitempty"`
}

// StreamLeaderboardParams defines parameters for StreamLeaderboard.
type StreamLeaderboardParams struct {
	// Category Optional category UUID to filter the streamed leaderboard.
	Category *openapi_types.UUID `form:"category,omitempty" json:"category,omitempty"`
}

// ListCompetitionsParams defines parameters for ListCompetitions.
type ListCompetitionsParams struct {
	// Status Filter by status (e.g. `live`, `open`). Omit to include all statuses.
	Status *CompetitionStatus `form:"status,omitempty" json:"status,omitempty"`
}

// OverrideAttemptJSONRequestBody defines body for OverrideAttempt for application/json ContentType.
type OverrideAttemptJSONRequestBody = AttemptOverride

// RequestMagicLinkJSONRequestBody defines body for RequestMagicLink for application/json ContentType.
type RequestMagicLinkJSONRequestBody = MagicLinkRequest

// UpdateCompetitionJSONRequestBody defines body for UpdateCompetition for application/json ContentType.
type UpdateCompetitionJSONRequestBody = CompetitionUpdate

// SubmitActionsJSONRequestBody defines body for SubmitActions for application/json ContentType.
type SubmitActionsJSONRequestBody = ActionsRequest

// CreateCategoryJSONRequestBody defines body for CreateCategory for application/json ContentType.
type CreateCategoryJSONRequestBody = CategoryCreate

// CreateEventJSONRequestBody defines body for CreateEvent for application/json ContentType.
type CreateEventJSONRequestBody = EventCreate

// CreateRegistrationJSONRequestBody defines body for CreateRegistration for application/json ContentType.
type CreateRegistrationJSONRequestBody = RegistrationCreate

// UpdateEventJSONRequestBody defines body for UpdateEvent for application/json ContentType.
type UpdateEventJSONRequestBody = EventUpdate

// CreateProblemJSONRequestBody defines body for CreateProblem for application/json ContentType.
type CreateProblemJSONRequestBody = ProblemCreate

// CreateCompetitionJSONRequestBody defines body for CreateCompetition for application/json ContentType.
type CreateCompetitionJSONRequestBody = CompetitionCreate

// UpdateProblemJSONRequestBody defines body for UpdateProblem for application/json ContentType.
type UpdateProblemJSONRequestBody = ProblemUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Replace an attempt's state directly
	// (POST /attempts/{id}/override)
	OverrideAttempt(w http.ResponseWriter, r *http.Request, id AttemptId)
	// Stamp an attempt as verified
	// (POST /attempts/{id}/verify)
	VerifyAttempt(w http.ResponseWriter, r *http.Request, id AttemptId)
	// Request a magic-link sign-in email
	// (POST /auth/magic/request)
	RequestMagicLink(w http.ResponseWriter, r *http.Request)
	// Get a competition by id
	// (GET /competitions/{id})
	GetCompetition(w http.ResponseWriter, r *http.Request, id CompetitionId)
	// Update a competition
	// (PATCH /competitions/{id})
	UpdateCompetition(w http.ResponseWriter, r *http.Request, id CompetitionId)
	// Submit one or more attempt actions
	// (POST /competitions/{id}/actions)
	SubmitActions(w http.ResponseWriter, r *http.Request, id CompetitionId)
	// List categories under a competition (sort order ASC)
	// (GET /competitions/{id}/categories)
	ListCategories(w http.ResponseWriter, r *http.Request, id CompetitionId)
	// Create a category
	// (POST /competitions/{id}/categories)
	CreateCategory(w http.ResponseWriter, r *http.Request, id CompetitionId)
	// List events under a competition (sequence ASC)
	// (GET /competitions/{id}/events)
	ListEvents(w http.ResponseWriter, r *http.Request, id CompetitionId)
	// Create an event under a competition
	// (POST /competitions/{id}/events)
	CreateEvent(w http.ResponseWriter, r *http.Request, id CompetitionId)
	// Get the comp leaderboard
	// (GET /competitions/{id}/leaderboard)
	GetLeaderboard(w http.ResponseWriter, r *http.Request, id CompetitionId, params GetLeaderboardParams)
	// Live leaderboard via Server-Sent Events
	// (GET /competitions/{id}/leaderboard/stream)
	StreamLeaderboard(w http.ResponseWriter, r *http.Request, id CompetitionId, params StreamLeaderboardParams)
	// List registrations for a competition
	// (GET /competitions/{id}/registrations)
	ListRegistrations(w http.ResponseWriter, r *http.Request, id CompetitionId)
	// Register self (or another climber, if staff) for a competition
	// (POST /competitions/{id}/registrations)
	CreateRegistration(w http.ResponseWriter, r *http.Request, id CompetitionId)
	// Update an event
	// (PATCH /events/{id})
	UpdateEvent(w http.ResponseWriter, r *http.Request, id EventId)
	// List problems under an event (sort order ASC)
	// (GET /events/{id}/problems)
	ListProblems(w http.ResponseWriter, r *http.Request, id EventId)
	// Create a problem under an event
	// (POST /events/{id}/problems)
	CreateProblem(w http.ResponseWriter, r *http.Request, id EventId)
	// List competitions at a location
	// (GET /locations/{locationId}/competitions)
	ListCompetitions(w http.ResponseWriter, r *http.Request, locationId LocationId, params ListCompetitionsParams)
	// Create a competition
	// (POST /locations/{locationId}/competitions)
	CreateCompetition(w http.ResponseWriter, r *http.Request, locationId LocationId)
	// Update a problem
	// (PATCH /problems/{id})
	UpdateProblem(w http.ResponseWriter, r *http.Request, id ProblemId)
	// Withdraw a registration (mark withdrawn)
	// (DELETE /registrations/{id})
	WithdrawRegistration(w http.ResponseWriter, r *http.Request, id RegistrationId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Replace an attempt's state directly
// (POST /attempts/{id}/override)
func (_ Unimplemented) OverrideAttempt(w http.ResponseWriter, r *http.Request, id AttemptId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stamp an attempt as verified
// (POST /attempts/{id}/verify)
func (_ Unimplemented) VerifyAttempt(w http.ResponseWriter, r *http.Request, id AttemptId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request a magic-link sign-in email
// (POST /auth/magic/request)
func (_ Unimplemented) RequestMagicLink(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a competition by id
// (GET /competitions/{id})
func (_ Unimplemented) GetCompetition(w http.ResponseWriter, r *http.Request, id CompetitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a competition
// (PATCH /competitions/{id})
func (_ Unimplemented) UpdateCompetition(w http.ResponseWriter, r *http.Request, id CompetitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Submit one or more attempt actions
// (POST /competitions/{id}/actions)
func (_ Unimplemented) SubmitActions(w http.ResponseWriter, r *http.Request, id CompetitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List categories under a competition (sort order ASC)
// (GET /competitions/{id}/categories)
func (_ Unimplemented) ListCategories(w http.ResponseWriter, r *http.Request, id CompetitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a category
// (POST /competitions/{id}/categories)
func (_ Unimplemented) CreateCategory(w http.ResponseWriter, r *http.Request, id CompetitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List events under a competition (sequence ASC)
// (GET /competitions/{id}/events)
func (_ Unimplemented) ListEvents(w http.ResponseWriter, r *http.Request, id CompetitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an event under a competition
// (POST /competitions/{id}/events)
func (_ Unimplemented) CreateEvent(w http.ResponseWriter, r *http.Request, id CompetitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the comp leaderboard
// (GET /competitions/{id}/leaderboard)
func (_ Unimplemented) GetLeaderboard(w http.ResponseWriter, r *http.Request, id CompetitionId, params GetLeaderboardParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Live leaderboard via Server-Sent Events
// (GET /competitions/{id}/leaderboard/stream)
func (_ Unimplemented) StreamLeaderboard(w http.ResponseWriter, r *http.Request, id CompetitionId, params StreamLeaderboardParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List registrations for a competition
// (GET /competitions/{id}/registrations)
func (_ Unimplemented) ListRegistrations(w http.ResponseWriter, r *http.Request, id CompetitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register self (or another climber, if staff) for a competition
// (POST /competitions/{id}/registrations)
func (_ Unimplemented) CreateRegistration(w http.ResponseWriter, r *http.Request, id CompetitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an event
// (PATCH /events/{id})
func (_ Unimplemented) UpdateEvent(w http.ResponseWriter, r *http.Request, id EventId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List problems under an event (sort order ASC)
// (GET /events/{id}/problems)
func (_ Unimplemented) ListProblems(w http.ResponseWriter, r *http.Request, id EventId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a problem under an event
// (POST /events/{id}/problems)
func (_ Unimplemented) CreateProblem(w http.ResponseWriter, r *http.Request, id EventId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List competitions at a location
// (GET /locations/{locationId}/competitions)
func (_ Unimplemented) ListCompetitions(w http.ResponseWriter, r *http.Request, locationId LocationId, params ListCompetitionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a competition
// (POST /locations/{locationId}/competitions)
func (_ Unimplemented) CreateCompetition(w http.ResponseWriter, r *http.Request, locationId LocationId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a problem
// (PATCH /problems/{id})
func (_ Unimplemented) UpdateProblem(w http.ResponseWriter, r *http.Request, id ProblemId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Withdraw a registration (mark withdrawn)
// (DELETE /registrations/{id})
func (_ Unimplemented) WithdrawRegistration(w http.ResponseWriter, r *http.Request, id RegistrationId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// OverrideAttempt operation middleware
func (siw *ServerInterfaceWrapper) OverrideAttempt(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AttemptId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OverrideAttempt(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyAttempt operation middleware
func (siw *ServerInterfaceWrapper) VerifyAttempt(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AttemptId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyAttempt(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestMagicLink operation middleware
func (siw *ServerInterfaceWrapper) RequestMagicLink(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestMagicLink(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCompetition operation middleware
func (siw *ServerInterfaceWrapper) GetCompetition(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCompetition(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCompetition operation middleware
func (siw *ServerInterfaceWrapper) UpdateCompetition(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCompetition(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitActions operation middleware
func (siw *ServerInterfaceWrapper) SubmitActions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitActions(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCategories operation middleware
func (siw *ServerInterfaceWrapper) ListCategories(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCategories(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCategory operation middleware
func (siw *ServerInterfaceWrapper) CreateCategory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCategory(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEvents operation middleware
func (siw *ServerInterfaceWrapper) ListEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEvents(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEvent operation middleware
func (siw *ServerInterfaceWrapper) CreateEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLeaderboard operation middleware
func (siw *ServerInterfaceWrapper) GetLeaderboard(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLeaderboardParams

	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "category", r.URL.Query(), &params.Category, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "category"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "category", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLeaderboard(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamLeaderboard operation middleware
func (siw *ServerInterfaceWrapper) StreamLeaderboard(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamLeaderboardParams

	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "category", r.URL.Query(), &params.Category, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "category"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "category", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamLeaderboard(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRegistrations operation middleware
func (siw *ServerInterfaceWrapper) ListRegistrations(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRegistrations(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRegistration operation middleware
func (siw *ServerInterfaceWrapper) CreateRegistration(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRegistration(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateEvent operation middleware
func (siw *ServerInterfaceWrapper) UpdateEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id EventId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProblems operation middleware
func (siw *ServerInterfaceWrapper) ListProblems(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id EventId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProblems(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProblem operation middleware
func (siw *ServerInterfaceWrapper) CreateProblem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id EventId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProblem(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCompetitions operation middleware
func (siw *ServerInterfaceWrapper) ListCompetitions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "locationId" -------------
	var locationId LocationId

	err = runtime.BindStyledParameterWithOptions("simple", "locationId", chi.URLParam(r, "locationId"), &locationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCompetitionsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCompetitions(w, r, locationId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCompetition operation middleware
func (siw *ServerInterfaceWrapper) CreateCompetition(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "locationId" -------------
	var locationId LocationId

	err = runtime.BindStyledParameterWithOptions("simple", "locationId", chi.URLParam(r, "locationId"), &locationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCompetition(w, r, locationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProblem operation middleware
func (siw *ServerInterfaceWrapper) UpdateProblem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ProblemId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProblem(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WithdrawRegistration operation middleware
func (siw *ServerInterfaceWrapper) WithdrawRegistration(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id RegistrationId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WithdrawRegistration(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/attempts/{id}/override", wrapper.OverrideAttempt)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/attempts/{id}/verify", wrapper.VerifyAttempt)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/magic/request", wrapper.RequestMagicLink)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/competitions/{id}", wrapper.GetCompetition)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/competitions/{id}", wrapper.UpdateCompetition)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/competitions/{id}/actions", wrapper.SubmitActions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/competitions/{id}/categories", wrapper.ListCategories)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/competitions/{id}/categories", wrapper.CreateCategory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/competitions/{id}/events", wrapper.ListEvents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/competitions/{id}/events", wrapper.CreateEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/competitions/{id}/leaderboard", wrapper.GetLeaderboard)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/competitions/{id}/leaderboard/stream", wrapper.StreamLeaderboard)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/competitions/{id}/registrations", wrapper.ListRegistrations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/competitions/{id}/registrations", wrapper.CreateRegistration)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/events/{id}", wrapper.UpdateEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events/{id}/problems", wrapper.ListProblems)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/events/{id}/problems", wrapper.CreateProblem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/locations/{locationId}/competitions", wrapper.ListCompetitions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/locations/{locationId}/competitions", wrapper.CreateCompetition)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/problems/{id}", wrapper.UpdateProblem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/registrations/{id}", wrapper.WithdrawRegistration)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H3vchu3suerdM2eKlPH/CPbOXfvlSpVaztOrs+VY5dln3zIeDXgTJODCANMAIxoxqWtfNoH2LrPcB8s",
	"T7KFBmY4Qw5FSrakk+R+sinib6P//LrRaH6KUlWUSqK0Jjr6FJVMswItavr01FosSvsycx8yNKnmpeVK",
	"RkfRc1WUaLn7BMw3g/fvX34zjoYRdw1KZvNoGElWYHQU8SwaRhp/rrjGLDqyusJhZNIcC+bGnildMBsd",
	"RVVFLe2ydL2M1VzOo8vLYXu+Xcu5zWW8uEC5kx7oGt3qMk5UyraRov7uqgWIVf/PW8gbraYCi10UKX2z",
	"W6XJW5xzYzXbh0V0q+0tLurSdTalkgZJnp6x7C3+XKGx7lOqpEVJ/2VlKbg/kslPxi33U2uav2icRUfR",
	"/5isZHXivzWTF1or7afqbvcVE255mIH2U8JUZUtQGri8YIJnwPS8Ktxg4+hyGH2r9JRnGcrbX9rTyuYo",
	"rRsVM5hWFqSywIRQC8zAKihRu7WDzbkBlrputMbvlf1WVTK7/SW+RaMqnSKtbObmpAW8l6yyudL8F7yD",
	"RbzixnA5b59ZqjFzpGPCndplzYxeW6cpltYvDD+yohTo/qvOPeNeDqNSqxK15Z4b3Refap6dKiWQycjz",
	"bM3wP7pGHxrGVtOfMLWOEE/pUJ66PfsJu0PzDItSWZTp8uwcl3vICi3O6Ygznu3VXGMp2BJ7BP2drhD4",
	"rM09Dwy0lgTnuISC2TTHDBiUmitdS8l4NVdDkmFkLLO46xyDtTyltut0bO2uHm47XV9aLDaJmgqO0p5Z",
	"XqCxrCg3d/6a/sPEMWhMlc5a0lUZzGCmNLg/Oxq6jTZEzpjFkRu4j9I9h9md9tRqJediSbMWBcoMs2NS",
	"qxdfwRwlahJ0v/6R4RmO4RT1BerYNa1KdOeUcsfZTIBGqzkaGPizg58rrBAewkyw8yVItAulzw/GsWzv",
	"4Atxlf/DjnOmZb1zLddPmbp3Jt1+yG/Rfb436WFBR6GsCrf0Sp5LtZBnYaBoGC3cqZ6lK7MZDSOCNmep",
	"UAbduFKd5dxYpZeOq+lIz5DU2Yc+E71VIMJythPrXTiXerVcphqd8YqG0S9KEt+qMhpGlcwUDWjQ9iyi",
	"Hs+07HCX+J7p/DlYLMx+3EASezmMCvbxpe/1t8NmcqY1W24QoJ5o+6bN2wAeela50rzXWGWtry/Xl+ZW",
	"tuLGa4zYMHHPkI3SXMNhldYOH9PXpJLwAvWywYhWVaSYp0uvwadOURM+22tZHSW86wgCPVrbv1I5z+ca",
	"58zvY31b/64WDreMPPg3qdJoIFXFlEsELq0C5j6WI4EXKNzuZebUMJxapTGLJTMw04gEfByAmAKXYHOE",
	"b54de0pwQ59TJpXkKROQYaoyr9eLcSxfoc1VNjIlpnzGU5hxFJmBQZJpVSZDSBbI57k17r8zLpkwZ16e",
	"eZYMY5lM0dgzmRwA0whKiiUUyCSX81kl6KCMKhAKmsV4/dvlSj/AJm2+VRrq0Y/gHLH0GyqYXIJV5Qbh",
	"3HEXXPLCSfuj5ii4tDhH7c7CbWnLRKYqztzXZzKZrGaVVTFFDWoGQi28i2Yc1sy4SZnOds+4RrEtk3sS",
	"Y3bmmydHsMh5mgefMJyg/268j/3y1G6rPlM55bzapNPU3UmjYX0SfQowMMHe6y+ZZkKgcMQKZ+R0p0yx",
	"I5RXE29DDDeFywvu6wvUmmc9euOZc18cF755ffoOJiHoYCafeHY5UaHbGN4RfYnxc9QYy0WuBBomEAgy",
	"pkhHELo/MEEP/fbrf7r/zWbujJgxjqnlPJZx5GFkCHFwA9Kxz0eWWuEV1DiO4CkINQeUVi+pf1kSCIrl",
	"gts8YNCvmzX2SE69mw4lD/soKZX1XWQlBJs6jO/d0k0so8ozjcwp0z6g7w3n2baZtwzfWgl1v2KCdWVb",
	"T7TWs7vQD9tZ47S2J9tJt7nI6+K/a9Psi9OpA4xuTrTnzOJc6eVzjb1k8xGOTz3QsBKBsFnGvT/xptWz",
	"s8vVdEZpe0a+xabkfoMzVgmvbg+dZ6YKbi1mLV+rIdcaMWiVvdtrwdJNluga6ivxQqvp5TBKiVrZGbMd",
	"drnSP0KZmWt1qFtdvbLWDr/1HcgX24uNBbIM9VQxnZ1dcMOnXHC73DXjyarXP1ad3HAhXLivFG3nrVbc",
	"zXsRV1Jup4rrjKdKlJ83nAMfnHweOePzXTKw5gQ74KJX4MuPAQOTsxIhQ2cRDCgJST2LE7TkoCUELWlq",
	"NdmUp+9ZgQ7IODtGeEk7yXJgdjmGZxUXdsSlOYLE6QinNjzg+4ge5mWYsmUyhjcN6KotkwHBL5AW2XL7",
	"POQxibdbm0QT1Xxzje/fnowMmyGQV89nHPUQKsl/rtChPahZatw7pGXaXk+mnBWvzDVk6tR3uBxGVZld",
	"U+bXlBQJQVtGggQE2jQCP+woprVT3uC+Zk9bxblNqJUa6iixzu526NFgZq9rYfdVSWo+v6Zi3R/qXDv6",
	"0VIbXwoZXJ+NhtEFaica2WdprWaQaW+oaGf/24c0IcbTJfrwJkinzUfX4e0aDfVEVVuKbk9W+GwruA/C",
	"WvPNupEB/+WUyzmg4POgEGDA5ghTJrMhzJ0DooeANh0fjGN5SmaIG+B0Y0GTiiU4m9nyfTKccYmwyJmF",
	"gp2jAYPSYCydynaU6tiAbehvB6Yjaq2RfaUxVyPVhNp1tFsA7s1B4F0Cuu1IjQnxehYd/XgjzPZheAUG",
	"T8pqKniadKD4nwa27QRbeyKcE7VAnTKDQ8j4nFszBCYzyJdljtIcQ1EZCnJqCz4KIMqcyapAzVOHekqn",
	"8bQb6X//yEa/HI7+7UP4d/Th0+HwX55c/uWLY6P9eKoHJV3NT5lmM7vGTn2O3CYgWodAPXhmh/hTRsYX",
	"UevXFvvPtQNdvj1TrdDXVQy8RR76GbozavcIX87AoB220D9Fl1sx6tY4FHmjUBh5A+NYfv/+5IQCxAbi",
	"qDLY9HZWxPFGHI3hBK0BBgbpRq/gH0MI0a3ZxHIwVZXIUMNDMCViBg/BKUSonPECJf2A4a5vtx4IccnN",
	"rb5Rxid+OEkMYXU38nHbJSH7tjMMfAP58zHVzVW9qoTlpeCoYZGjhMZiObPevkYI1weBilZZJlp+k49s",
	"X9PM1qTa5kOENe8Qvm8bw7eZawPk+Y4hMVzOBSbwNR0obWwIid+M+2vhyRC+MhSxNQgaDSmY+g7FHVHS",
	"MurBH23C4jSLv4bkHdSwOojWykPiUp/iEErv5XS0bwJ2KoG5Zl4Gdw67rz/Fpih67uJzpW3L6QaTq4V0",
	"WjoV3PGJgQGO52OIo1eP4mgIcfTsf8bRQa8fXiou+24K3ht/PxeCCiEIcQx8LpUOXzWxB7KKddBhuxjX",
	"XDyMtKos9t6w1PkNILg8p5gHUGMD1o0IWi1gMF8WwKU7G6WXB32XLLsVyZVwNjgoK+Ls2FGfXDa8Ux9k",
	"Z9IdUtfOdNtk4CmfnoWp9/Ll0uAa7cvJN7CsN4mqZtyUgi3Pauu5xuaSlSZXFpjtJvO54cafYaxLxj/P",
	"G68M6n3psmD8AvWZ4XP5mTEAZ9cyzRbyM0bZy360uWW12bXj6pz4DmY+bcBprckJTUbDyDkGTj74BY1Y",
	"55wwneb8onPr0avh31NwYJN1ngpRXxCqoE/G8FqKZf3XUqOhy1qPE+r0SaYxliHiMIZ3TqEi08CgJqvv",
	"P3Qucwb4sRQ85Za+7b3x+527pze6SPhvD/NqD/M+fMJreoJ9d/c+g7WbdurTwI7aGmSVTBttJKNiPcRa",
	"Vk1VMDnSyDKSMGoFBRrD5jiGV5TD6f0W/MgNIWdCBAvU54DyAoUq++zBmq5bz1lrbc0Z6m0hpmtL4pd2",
	"Bfd3/a50lu7M42lHDR6Nt9wFb8FN+3kuW8/wGubg2Cc/lVpdcEqv8l8zjVDr/w11fu+scPOowLX86ltk",
	"lc3j39hDy7D0eG5dILt2Z/r+5MR72U5ZtMwamJJJA0wICANwNDfyGm4UcqJU572TLlv7fyGtXvalXTYJ",
	"19ezB1ebqDVZ3ICFa3G8zhpW2/xw9ZH6LW29fjyz6sz6rL9Nzms3ooTg3la37RutOy17e9Q1xAsX+jDT",
	"qmiiVA9M8LDHsOZ5x7LlXB+3nW7N5DmlGwysKs0Q3F/NsM5jMwe+p0B2QfaTUtzgsHO90/LImTzfXPOj",
	"EZcZfsTsGNxRgcmdhiTxUgvUtAQYPHr8+Cv6L5fzg76Mnxtfx5rtzrnZ4xqKNtV3LbnmyoQjC1PW4w83",
	"2LKHB3fw+z86gLpL3B9yBSmTYBDXNdZRLEerO5zffv1PYHKpJMIgBF6Pw+MWAycvvp28Uobx1A0wrxBK",
	"weQBDVAghYM6I9BFhdJzCF/mvHR80WLEOs2BhqhpJ20YhuxmE2jyX6MOL0+Iy9wwnbid30c0jMKUrSNx",
	"ZO9z8l6xOU9PuDxvJfG3kWfBuHDI06/jf4WvxqkqnBrHj46vSLtOPFFGjw8f/0sPJPXjbDwvyhFYlmk0",
	"BGM0psgv/CE5R37EJYWnOibED0XPA05Qzm0eHT3+21d9qIBWtzXuVTKb+0kzrjG1FAObWdRgqjRFY2aV",
	"AJ8PENJrYvmqMhamCAw0CmbdWmmYgVRAdgWHIBXkytgDfxVM7ziAHpwxiyaWF5xBYtgM34Z5fVBvxoQw",
	"MGUpxeKSScZMThxKV0HhyVqI0tbH00P4neCciNcnSyGIuw2e7x/K3T8624Rdr1Dt14pw/nMFJ/32rqD1",
	"LcPo/z6yvY5s43TaIeFt4tAFP+tP+NhsNmLGhyJhyqdjeF7rcYNiNqqVuXOxTa4qEdCDD3BFwztAU/1K",
	"cQxtr9Kp4cqgfmCg3b03JNwK1e47dMqEcBRwXcdwipZCDgwyPpuhRmljGUaFIFYGkvmyOCuYZHPUDxPQ",
	"SuAWo7rXm8Z1KN4i6qbckveWVprb5Snp+vBOh2nUTytnh+pP9VVe9Pcf3kXDnqchhZpygTCBp29ehrec",
	"Zgyvp5ZxCWQhwsOMkk8uHk1YZfOJUHMuk1gONNpKSwMJIzN1ZtU5ygQeOgwx02jy8JeDMfw7IZ2jWCZP",
	"w1tros0RPKN1QlwdHj5Jf1pY+g+Ga0BvyaKjsJsV2XJrS++dqXOO9Z43tzfVamFQwwRO3zxd7e8ULbDK",
	"qoJZnlLKlLe3rGVxY1kyYxZKZ0AbhkEghd/+ATjqOcwyonsrss/LWA6S7168g4n/OKIGtH9rSwpHP4RT",
	"VuApt/j1CfvoPrqTRBhwKqiQhWtxKlvgd7cqXHCmF2cGjfGJprWLWPL/wKV/ac7lTG0S4u2L03d0vg6v",
	"va0DaQ88bKujeFaz9JzYXmZgqrJU2l9Zy8zrsHEs37Xeq4WX9GoGVlc2p7GnygGZHOE7VeONQeJUhZZM",
	"EAslw4A7FCv5KFUZzpHepsmMOp5eoLD4H9yGs4JBssDpxJRsYnQ6EXy6NkyJ0o1EmQe0ZUfst5WEpGDn",
	"CO47N4OHV7UD6087lqbEFNKcyTmaY3j+EmaMC+NfmZMY+yhW67XzjAs0kGk+s+NYxvJNzgzCI4RSlZVw",
	"uKrNE05aaGuUQPH87ftvgBlgQNkKKLORVSOUWSyN4PSCiVnAj6hTbkL8c1YJASUvUXDnCtCCf/u//88R",
	"mLZMH96drj7EkhhdSVMVdP4HYwiLnDmAa8LtR8G4dMdLK2vOGAb+tn4Yy5DGaYadmzgz9LpYUm5qeAPV",
	"9B92UOrQe6PrkZmHcHr6AozVyIrA7JZbQpENbzpujSgH1ngWPhw/Gh86gQ8HHh1FT8aH4yc+4yon/bfl",
	"8dh6AZwtaVKrJpNVgZzLDw5OmB7w7owE6odbVL6ThpRPxRIMWtN+muYfpo1j+d44u2PQHIHjm5Hk89zS",
	"7ZOsyiGZucpSvoQSFZEzPP/3MhrLekDimgUzUHBjMAMuQSMT/s6UHs7VlHCi6xNtwxO2ZO0NW9LIIUut",
	"ctbWmT3g2RCMt5SsyriNpdWMC0pCMD6tNCSa1o6BAyhNyZaofv1Xp6J7U4fGPlPZ8osV3Fh/anjZtamh",
	"WEancsvjw8MvNn1Pyn1P8Q8PtLOaGyhB8yu/ir7Bm9VOWkVmqMuj3V06ZU2o05PdnVYFY6jHV7t7NOVb",
	"CJZURcH0kmqt+GeZTG68yvTeplg6yWdzsxZ6NNEHN9KaNHt7ei+y7NCzATWbgZLA6kDIA9OU42hkkYCF",
	"gaSVu09oqPUgIHGDtPTBMWTKOeNSWShUxmfLOkEveFZ9AvUPIkZbnP4JmfqfnkNPLSvKFn8621yf1A7W",
	"dCiY7PxEtypO9DLXdwE7UMIkZbONKrMKKhFAJrVLARED3NZeSQhHjWP5VCzY0vGbh9uPDx9TSMdbcr9L",
	"egSQ+fpLAhY52hy1g6iOsWyOsaTxXbNVAI/UuicAS89RQ8rkAwtI+cyEk9JUVR77xfKELSnqR98IXnBr",
	"juiN/8s3MGguah8fTgouPfShRqgJ3tFrg5FfxOAJTODR36DgcggonbH0houAJeoLh4bYnHFpbCiWcNAn",
	"B0EjNpHDW7IsG5HJvUzL4y9n2eoSUL0lrUIeS2gDA09iSlfJ6cm6IT9uytLzuXZi4EvvHIw7fmR09OOH",
	"rvoO47bxbM20deCzFhF32EE02tJCmtttbo5Ege7hfYf2eacKzV1osT4Svgs6PzT5HPV1c2X0nfNIOw7Z",
	"dAn8Cj00vKYh7JZaJGPIbNrjNr+9QYQDVoHCWFKdkf2jhT1y7Q3KOnd8ecHezCu7P9B4lWHd5M4/ImL0",
	"u+1KwdV2eEPZTFp1nj5bPHrN+fvg+S40t9g4vuEmDFvgkO52qQYNvGBpXS4klvRYzz8cR2nJ8jeVway/",
	"tdssmkYXxyyWVCxtFIqlQZkrGeqfLMGwGYrlGEKRKRKxUqsUg1MYSwpVH1OMo3LynSln7NlUaS/UviST",
	"s/R+DB9U8PeSTWWucLGYZW3gNFiqCtxKM2+1/VWkv7J2zQumz+muGsKLz0aPhKpR9UCENqizVWWrL2Vu",
	"Dnjhsy/Fkv5q/JB8FgpNamTZ0k9dyUz57hovUDeQyvsfU5ypcKddKGPpsk/aVbGXcAtqMOz2F9TKl7Oy",
	"OQHz+tqzLm41CMceHqLEEmCunfOz4DJTi6HDYeQhHzjqvlwVgjvydppRWT1I1krEJfQ6IlTK3KytF/BR",
	"51F/IOSZUPPkuGaNGjcSDEz9Afh3GP60uwHZlAmB2j90o0cGhDJXIaB6JeCrazmFH1jOv/CoiTJFoeSc",
	"Yuysrp7rWyQhrSqBnBkfZnXApa7W5e+rffE4SNq16ZJeFHhaTQtuA9/fVnChW1/ujs3EeuG4HlPxBvUo",
	"ROPqJzalqOpon/sDxY3aQahVlbYm2relTFss/7hWx3MPPWKi6xC9CtWxhqWuZYNWCWdbse8JN/b5qtln",
	"ss5eSWZ9z+Y3S3ht8NXzVvbcfeBiR6lWCl94Q9hFygPjTBiZN3h6+vzgVkFzLyq4CWbe0GP+hrc5nFuC",
	"vN0CUnspske3gXdXTLiV6ZYQHpz8gUGvPwfH0Ktzv5a28Rc2V2qaF77JHWsZ/4R7DxXjl+fl15ueVSnC",
	"e1M5oZRkv7oJy7t3ZZMjy86Mj17fSNn4M7odTdN+Y3F/aiZw4Rau+xMpmBqC93D0dVWO6ObrB72z+Vac",
	"3vA6B7flgPgL5/Z9cEXV8MOlI7/AWIbqZ4O2Z2PGawXWoEmfTGrVmcDPFaHZGRcWNUimtVqQB0JFB0Kz",
	"Y1A2R73g9Bzdr8wnVpfOv+o8PNU4ZzoTaAyoWTOCUwH1nSd+LDG1/nL8KJYOU9PT91HT2O3CgHORK1NR",
	"ssmCSY84ab1+2qa5VTB3o6NTDc4dqosKmwNy1962Iv7BmfO5FlSDnUD9/3kMBlMlM3PsmwA3sQypmzTm",
	"IkfpoD958d5tECyUsqtPqc/X+g5t+7XGhorbkuHabI78XKsgnFDIIDfND3UQQVYJLy2juP/vc3y4RU+s",
	"vfk+4OK5Pmsz+P3Fk/vE7fbM1U5dMfE5H1tVxomS85HgF5hBYvGj9dBm5HslkCopsRMLASy4NcBimbSm",
	"SYKiU7LuAgMuueVMgAkPzH3CEZOkCPq7+4QwX8Q8SMgkJHnBZJVSoWQsG4GBpxAqYTO3jwT8DydQgWEM",
	"uUR+xCeHtYTG0igfpfKxk4+8Cc2dcyGAZwJbe/dXcc98WpsJiT7oM/XIpJ1SXlZy5JolSfKTiaVrZAEN",
	"fA0SF9BqNkjqxL7Oyf1ly9ElB8exRDNmWUaDOKSEEvXgQavtgyEgfO3T+OBTLAH8/F7bfw1/P339/bhk",
	"2uAAxxmzzA0KMJnAb7/+l8aRphpnv/36X7G8dF8lSeL28i5HyJnMBGrwT4lDRM8tzOfNiCUduk8cy7gJ",
	"VIvloE4DtGzqO2cUk0vQjOnj4CDxyvV1ifLpm5fwZHxIF/PuGAqVoaCkpUbqYIFCHHcuYJ3ZcjqC4l6L",
	"upZbWOVf/1qypVAsc1YEWZpDh+ViSTz3178O6+taWHBNurxgFrg1KGa9oS/a/ZfUyCuarmuxO9XQG/L/",
	"xVT0C2PZVHCTe1mknyxwE4QwfZ8qyBkpGce4kDiOPUqgPk96k1MDmOSk3dkvqAme3bkXc9HNu3MqwuvN",
	"0anbVeMV3qk96CQTbjUFT+WSMghWvydFiWgpkyC4sT6trbW50aqKQYP+Bgt2gfDVAcydspYGcrWAokpz",
	"yNAyLqCSbDbjgjfjGzCIfWLm9NzbzsLv2Jfu1IbZw6XuLPYevejOaRM03dPxuC3f+Qduc5AKkpDPn9Tl",
	"PeqkGNP3IMAB/VgO1oJ7/a72ARRsCSUzBthqmlj6BGSag35xg6pmCdPLb95n6xz67fjoPQ9M7s9V7zL5",
	"1Uz9x3TcXYd/u/1foAtPgOor060vOlcpB2uZnTUbo5jBwAm1B9L17fcQ+Czcd15H5p3B8GG3JnHoekqg",
	"/hnPvZJbPiN25hMVbj12du8pKVtjZ3Veii8a+cfPSAmxs71Zd1I/nrgyLP+mbnTHYKIukrgHjqiXeI8Q",
	"oiZlHbis45i3d+nXUSO3HYF/0/ww323oke5T6vsz7Q3LbWWxP9NVX51s0eXoq7VLzUdm8mn1M8+XHQfr",
	"6myDdsMdQYJvvQM1XYKvJxZqiyYU0xr6R3cUgS98sjqXqagypGo7vgdujeg2v35xbR5qSpV9uGN9uY+i",
	"JFWlZm2gY4YgcYHGwoxr87t5FeETLlrbcAqNNXrsy6nZ1q+df15ixc6MirvMI753VbvtWqK+vf696Nk7",
	"8INORTVvnCAunbfveYq37fa2fI19XZoawNzQqVn9Fv/duDV3Akju3bW5ApDUzk04tz9Dwv3q16Gv4ONO",
	"LK9h5gwF9v4ecCuLeIobScT10+LXb6E3qhbLjScmp2pmwU+3ev2mFg5xLENsscq49Q/Up3way/DjsNz/",
	"BK8Pbmis+mNuP4RayxtRtw4zftUfUqQizb8XC18vmGpHtUJqA0q1b2pOf0GPqk1TfzfQfXnWrV3y44fL",
	"4adOZY8fPzjd57Mc+gBrqVVWpeHEKi1CgRBzNJk0dWPHM7EcZ3gRucG73Y1lcy7n2/uOMry4or/jUQHu",
	"u/YIRxMC7SJXxh796+G/HpICDxTduPBYXXa4o6AaHL7QBwg+w3SZCoRBXZBk6B/lUUWyIfz9h3cQ6q1Q",
	"Kb6AtOlR3uZi36n6h0CaohTjcBc0bCXaDmFrAQi6Og+PsyFnck5vo22OBlvTd1jm8sPl/w8AAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
