// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
	CookieAuthScopes cookieAuthContextKey = "cookieAuth.Scopes"
)

// Defines values for AggregationMethod.
const (
	BestN          AggregationMethod = "best_n"
	Sum            AggregationMethod = "sum"
	SumDropN       AggregationMethod = "sum_drop_n"
	WeightedFinals AggregationMethod = "weighted_finals"
)

// Valid indicates whether the value is a known member of the AggregationMethod enum.
func (e AggregationMethod) Valid() bool {
	switch e {
	case BestN:
		return true
	case Sum:
		return true
	case SumDropN:
		return true
	case WeightedFinals:
		return true
	default:
		return false
	}
}

// Defines values for CompetitionFormat.
const (
	Series CompetitionFormat = "series"
	Single CompetitionFormat = "single"
)

// Valid indicates whether the value is a known member of the CompetitionFormat enum.
func (e CompetitionFormat) Valid() bool {
	switch e {
	case Series:
		return true
	case Single:
		return true
	default:
		return false
	}
}

// Defines values for CompetitionStatus.
const (
	Archived CompetitionStatus = "archived"
	Closed   CompetitionStatus = "closed"
	Draft    CompetitionStatus = "draft"
	Live     CompetitionStatus = "live"
	Open     CompetitionStatus = "open"
)

// Valid indicates whether the value is a known member of the CompetitionStatus enum.
func (e CompetitionStatus) Valid() bool {
	switch e {
	case Archived:
		return true
	case Closed:
		return true
	case Draft:
		return true
	case Live:
		return true
	case Open:
		return true
	default:
		return false
	}
}

// Defines values for LeaderboardVisibility.
const (
	Members     LeaderboardVisibility = "members"
	Public      LeaderboardVisibility = "public"
	Registrants LeaderboardVisibility = "registrants"
)

// Valid indicates whether the value is a known member of the LeaderboardVisibility enum.
func (e LeaderboardVisibility) Valid() bool {
	switch e {
	case Members:
		return true
	case Public:
		return true
	case Registrants:
		return true
	default:
		return false
	}
}

// Accepted defines model for Accepted.
type Accepted struct {
	Ok bool `json:"ok"`
}

// Aggregation How per-event scores combine into a comp-level standing. Stored
// as freeform jsonb in the DB; this is the canonical decoded form.
// Method-specific fields (`drop`, `weights`, `finals_event_id`,
// `best_n`) are only meaningful for some methods.
type Aggregation struct {
	// BestN For `best_n`: keep this many top per-event scores.
	BestN *int `json:"best_n,omitempty"`

	// Drop For `sum_drop_n`/`best_n`: number of low events to discard.
	Drop *int `json:"drop,omitempty"`

	// FinalsEventId For `weighted_finals`: which event is the finals.
	FinalsEventId *openapi_types.UUID `json:"finals_event_id,omitempty"`
	Method        *AggregationMethod  `json:"method,omitempty"`

	// Weights For `weighted_finals`: parallel to event sequence.
	Weights *[]int `json:"weights,omitempty"`
}

// AggregationMethod defines model for Aggregation.Method.
type AggregationMethod string

// CategoryCreate defines model for CategoryCreate.
type CategoryCreate struct {
	Name  string                  `json:"name"`
	Rules *map[string]interface{} `json:"rules,omitempty"`

	// SortOrder Defaults to 0 if omitted.
	SortOrder *int `json:"sort_order,omitempty"`
}

// Competition defines model for Competition.
type Competition struct {
	// Aggregation How per-event scores combine into a comp-level standing. Stored
	// as freeform jsonb in the DB; this is the canonical decoded form.
	// Method-specific fields (`drop`, `weights`, `finals_event_id`,
	// `best_n`) are only meaningful for some methods.
	Aggregation Aggregation `json:"aggregation"`
	CreatedAt   time.Time   `json:"created_at"`
	EndsAt      time.Time   `json:"ends_at"`

	// Format Comp shape. `single` = one event, `series` = multiple events
	// whose results combine per `aggregation`.
	Format CompetitionFormat  `json:"format"`
	Id     openapi_types.UUID `json:"id"`

	// LeaderboardVisibility Who can see the leaderboard:
	// - `public` — anyone (default; matches LEF/Mosaic league plan)
	// - `members` — anyone with org membership at the comp's location
	// - `registrants` — only climbers registered for this comp
	LeaderboardVisibility LeaderboardVisibility `json:"leaderboard_visibility"`
	LocationId            openapi_types.UUID    `json:"location_id"`
	Name                  string                `json:"name"`
	RegistrationClosesAt  *time.Time            `json:"registration_closes_at,omitempty"`
	RegistrationOpensAt   *time.Time            `json:"registration_opens_at,omitempty"`

	// ScoringConfig Scorer-specific config (shape depends on `scoring_rule`).
	ScoringConfig map[string]interface{} `json:"scoring_config"`

	// ScoringRule Name of the scorer to apply. Built-ins: `top_zone`, `fixed`,
	// `decay`. Per-event overrides live on `competition_events`.
	ScoringRule string `json:"scoring_rule"`

	// Slug URL-safe identifier, unique per location.
	Slug      string            `json:"slug"`
	StartsAt  time.Time         `json:"starts_at"`
	Status    CompetitionStatus `json:"status"`
	UpdatedAt time.Time         `json:"updated_at"`
}

// CompetitionCategory defines model for CompetitionCategory.
type CompetitionCategory struct {
	CompetitionId openapi_types.UUID `json:"competition_id"`
	Id            openapi_types.UUID `json:"id"`
	Name          string             `json:"name"`

	// Rules Freeform jsonb describing eligibility (age band, gender, etc.).
	// Shape is intentionally open — staff define what makes sense
	// per comp.
	Rules     map[string]interface{} `json:"rules"`
	SortOrder int                    `json:"sort_order"`
}

// CompetitionCreate defines model for CompetitionCreate.
type CompetitionCreate struct {
	// Aggregation How per-event scores combine into a comp-level standing. Stored
	// as freeform jsonb in the DB; this is the canonical decoded form.
	// Method-specific fields (`drop`, `weights`, `finals_event_id`,
	// `best_n`) are only meaningful for some methods.
	Aggregation *Aggregation `json:"aggregation,omitempty"`
	EndsAt      time.Time    `json:"ends_at"`

	// Format Comp shape. `single` = one event, `series` = multiple events
	// whose results combine per `aggregation`.
	Format CompetitionFormat `json:"format"`

	// LeaderboardVisibility Defaults to `public` if omitted.
	LeaderboardVisibility *LeaderboardVisibility  `json:"leaderboard_visibility,omitempty"`
	Name                  string                  `json:"name"`
	RegistrationClosesAt  *time.Time              `json:"registration_closes_at,omitempty"`
	RegistrationOpensAt   *time.Time              `json:"registration_opens_at,omitempty"`
	ScoringConfig         *map[string]interface{} `json:"scoring_config,omitempty"`
	ScoringRule           string                  `json:"scoring_rule"`

	// Slug Lowercase, digits, and hyphens; must start with alphanumeric.
	Slug     string    `json:"slug"`
	StartsAt time.Time `json:"starts_at"`

	// Status Defaults to `draft` if omitted.
	Status *CompetitionStatus `json:"status,omitempty"`
}

// CompetitionEvent defines model for CompetitionEvent.
type CompetitionEvent struct {
	CompetitionId         openapi_types.UUID      `json:"competition_id"`
	EndsAt                time.Time               `json:"ends_at"`
	Id                    openapi_types.UUID      `json:"id"`
	Name                  string                  `json:"name"`
	ScoringConfigOverride *map[string]interface{} `json:"scoring_config_override,omitempty"`

	// ScoringRuleOverride If set, overrides the comp-level scoring_rule for this event.
	// NULL means "use the comp default". Lets a series mix event types
	// (boulder + speed + lead under one comp).
	ScoringRuleOverride *string `json:"scoring_rule_override,omitempty"`

	// Sequence Position within the comp; unique per comp.
	Sequence int       `json:"sequence"`
	StartsAt time.Time `json:"starts_at"`

	// Weight Multiplier when aggregating event scores into a series total.
	Weight float32 `json:"weight"`
}

// CompetitionFormat Comp shape. `single` = one event, `series` = multiple events
// whose results combine per `aggregation`.
type CompetitionFormat string

// CompetitionProblem defines model for CompetitionProblem.
type CompetitionProblem struct {
	Color   *string            `json:"color,omitempty"`
	EventId openapi_types.UUID `json:"event_id"`
	Grade   *string            `json:"grade,omitempty"`
	Id      openapi_types.UUID `json:"id"`

	// Label Short identifier shown to climbers (e.g. "M1", "B7").
	Label string `json:"label"`

	// Points Used by `fixed` scorer; ignored by `top_zone` and `decay`.
	Points *float32 `json:"points,omitempty"`

	// RouteId Optional link to a routes table row (gym inventory).
	RouteId    *openapi_types.UUID `json:"route_id,omitempty"`
	SortOrder  int                 `json:"sort_order"`
	ZonePoints *float32            `json:"zone_points,omitempty"`
}

// CompetitionStatus defines model for CompetitionStatus.
type CompetitionStatus string

// CompetitionUpdate All fields optional. Only fields present in the request are
// updated. To clear a nullable field, send explicit null.
type CompetitionUpdate struct {
	// Aggregation How per-event scores combine into a comp-level standing. Stored
	// as freeform jsonb in the DB; this is the canonical decoded form.
	// Method-specific fields (`drop`, `weights`, `finals_event_id`,
	// `best_n`) are only meaningful for some methods.
	Aggregation *Aggregation `json:"aggregation,omitempty"`
	EndsAt      *time.Time   `json:"ends_at,omitempty"`

	// Format Comp shape. `single` = one event, `series` = multiple events
	// whose results combine per `aggregation`.
	Format *CompetitionFormat `json:"format,omitempty"`

	// LeaderboardVisibility Who can see the leaderboard:
	// - `public` — anyone (default; matches LEF/Mosaic league plan)
	// - `members` — anyone with org membership at the comp's location
	// - `registrants` — only climbers registered for this comp
	LeaderboardVisibility *LeaderboardVisibility  `json:"leaderboard_visibility,omitempty"`
	Name                  *string                 `json:"name,omitempty"`
	RegistrationClosesAt  *time.Time              `json:"registration_closes_at,omitempty"`
	RegistrationOpensAt   *time.Time              `json:"registration_opens_at,omitempty"`
	ScoringConfig         *map[string]interface{} `json:"scoring_config,omitempty"`
	ScoringRule           *string                 `json:"scoring_rule,omitempty"`
	Slug                  *string                 `json:"slug,omitempty"`
	StartsAt              *time.Time              `json:"starts_at,omitempty"`
	Status                *CompetitionStatus      `json:"status,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Error Human-readable error message. Matches the existing routewerk envelope.
	Error string `json:"error"`
}

// EventCreate defines model for EventCreate.
type EventCreate struct {
	EndsAt                time.Time               `json:"ends_at"`
	Name                  string                  `json:"name"`
	ScoringConfigOverride *map[string]interface{} `json:"scoring_config_override,omitempty"`
	ScoringRuleOverride   *string                 `json:"scoring_rule_override,omitempty"`
	Sequence              int                     `json:"sequence"`
	StartsAt              time.Time               `json:"starts_at"`

	// Weight Defaults to 1.0 if omitted.
	Weight *float32 `json:"weight,omitempty"`
}

// EventUpdate All fields optional; only provided fields are updated.
type EventUpdate struct {
	EndsAt                *time.Time              `json:"ends_at,omitempty"`
	Name                  *string                 `json:"name,omitempty"`
	ScoringConfigOverride *map[string]interface{} `json:"scoring_config_override,omitempty"`
	ScoringRuleOverride   *string                 `json:"scoring_rule_override,omitempty"`
	Sequence              *int                    `json:"sequence,omitempty"`
	StartsAt              *time.Time              `json:"starts_at,omitempty"`
	Weight                *float32                `json:"weight,omitempty"`
}

// LeaderboardVisibility Who can see the leaderboard:
// - `public` — anyone (default; matches LEF/Mosaic league plan)
// - `members` — anyone with org membership at the comp's location
// - `registrants` — only climbers registered for this comp
type LeaderboardVisibility string

// MagicLinkRequest defines model for MagicLinkRequest.
type MagicLinkRequest struct {
	// Email The address to receive the sign-in link.
	Email openapi_types.Email `json:"email"`

	// Next Optional path to redirect to after successful verification.
	// Must be a relative path (no scheme, no host) — server validates
	// via `safeRedirect` and falls back to `/dashboard` if invalid.
	Next *string `json:"next,omitempty"`
}

// ProblemCreate defines model for ProblemCreate.
type ProblemCreate struct {
	Color      *string             `json:"color,omitempty"`
	Grade      *string             `json:"grade,omitempty"`
	Label      string              `json:"label"`
	Points     *float32            `json:"points,omitempty"`
	RouteId    *openapi_types.UUID `json:"route_id,omitempty"`
	SortOrder  *int                `json:"sort_order,omitempty"`
	ZonePoints *float32            `json:"zone_points,omitempty"`
}

// ProblemUpdate All fields optional; only provided fields are updated.
type ProblemUpdate struct {
	Color      *string             `json:"color,omitempty"`
	Grade      *string             `json:"grade,omitempty"`
	Label      *string             `json:"label,omitempty"`
	Points     *float32            `json:"points,omitempty"`
	RouteId    *openapi_types.UUID `json:"route_id,omitempty"`
	SortOrder  *int                `json:"sort_order,omitempty"`
	ZonePoints *float32            `json:"zone_points,omitempty"`
}

// CompetitionId defines model for CompetitionId.
type CompetitionId = openapi_types.UUID

// EventId defines model for EventId.
type EventId = openapi_types.UUID

// LocationId defines model for LocationId.
type LocationId = openapi_types.UUID

// ProblemId defines model for ProblemId.
type ProblemId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// cookieAuthContextKey is the context key for cookieAuth security scheme
type cookieAuthContextKey string

// ListCompetitionsParams defines parameters for ListCompetitions.
type ListCompetitionsParams struct {
	// Status Filter by status (e.g. `live`, `open`). Omit to include all statuses.
	Status *CompetitionStatus `form:"status,omitempty" json:"status,omitempty"`
}

// RequestMagicLinkJSONRequestBody defines body for RequestMagicLink for application/json ContentType.
type RequestMagicLinkJSONRequestBody = MagicLinkRequest

// UpdateCompetitionJSONRequestBody defines body for UpdateCompetition for application/json ContentType.
type UpdateCompetitionJSONRequestBody = CompetitionUpdate

// CreateCategoryJSONRequestBody defines body for CreateCategory for application/json ContentType.
type CreateCategoryJSONRequestBody = CategoryCreate

// CreateEventJSONRequestBody defines body for CreateEvent for application/json ContentType.
type CreateEventJSONRequestBody = EventCreate

// UpdateEventJSONRequestBody defines body for UpdateEvent for application/json ContentType.
type UpdateEventJSONRequestBody = EventUpdate

// CreateProblemJSONRequestBody defines body for CreateProblem for application/json ContentType.
type CreateProblemJSONRequestBody = ProblemCreate

// CreateCompetitionJSONRequestBody defines body for CreateCompetition for application/json ContentType.
type CreateCompetitionJSONRequestBody = CompetitionCreate

// UpdateProblemJSONRequestBody defines body for UpdateProblem for application/json ContentType.
type UpdateProblemJSONRequestBody = ProblemUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Request a magic-link sign-in email
	// (POST /auth/magic/request)
	RequestMagicLink(w http.ResponseWriter, r *http.Request)
	// Get a competition by id
	// (GET /competitions/{id})
	GetCompetition(w http.ResponseWriter, r *http.Request, id CompetitionId)
	// Update a competition
	// (PATCH /competitions/{id})
	UpdateCompetition(w http.ResponseWriter, r *http.Request, id CompetitionId)
	// List categories under a competition (sort order ASC)
	// (GET /competitions/{id}/categories)
	ListCategories(w http.ResponseWriter, r *http.Request, id CompetitionId)
	// Create a category
	// (POST /competitions/{id}/categories)
	CreateCategory(w http.ResponseWriter, r *http.Request, id CompetitionId)
	// List events under a competition (sequence ASC)
	// (GET /competitions/{id}/events)
	ListEvents(w http.ResponseWriter, r *http.Request, id CompetitionId)
	// Create an event under a competition
	// (POST /competitions/{id}/events)
	CreateEvent(w http.ResponseWriter, r *http.Request, id CompetitionId)
	// Update an event
	// (PATCH /events/{id})
	UpdateEvent(w http.ResponseWriter, r *http.Request, id EventId)
	// List problems under an event (sort order ASC)
	// (GET /events/{id}/problems)
	ListProblems(w http.ResponseWriter, r *http.Request, id EventId)
	// Create a problem under an event
	// (POST /events/{id}/problems)
	CreateProblem(w http.ResponseWriter, r *http.Request, id EventId)
	// List competitions at a location
	// (GET /locations/{locationId}/competitions)
	ListCompetitions(w http.ResponseWriter, r *http.Request, locationId LocationId, params ListCompetitionsParams)
	// Create a competition
	// (POST /locations/{locationId}/competitions)
	CreateCompetition(w http.ResponseWriter, r *http.Request, locationId LocationId)
	// Update a problem
	// (PATCH /problems/{id})
	UpdateProblem(w http.ResponseWriter, r *http.Request, id ProblemId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Request a magic-link sign-in email
// (POST /auth/magic/request)
func (_ Unimplemented) RequestMagicLink(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a competition by id
// (GET /competitions/{id})
func (_ Unimplemented) GetCompetition(w http.ResponseWriter, r *http.Request, id CompetitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a competition
// (PATCH /competitions/{id})
func (_ Unimplemented) UpdateCompetition(w http.ResponseWriter, r *http.Request, id CompetitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List categories under a competition (sort order ASC)
// (GET /competitions/{id}/categories)
func (_ Unimplemented) ListCategories(w http.ResponseWriter, r *http.Request, id CompetitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a category
// (POST /competitions/{id}/categories)
func (_ Unimplemented) CreateCategory(w http.ResponseWriter, r *http.Request, id CompetitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List events under a competition (sequence ASC)
// (GET /competitions/{id}/events)
func (_ Unimplemented) ListEvents(w http.ResponseWriter, r *http.Request, id CompetitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an event under a competition
// (POST /competitions/{id}/events)
func (_ Unimplemented) CreateEvent(w http.ResponseWriter, r *http.Request, id CompetitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an event
// (PATCH /events/{id})
func (_ Unimplemented) UpdateEvent(w http.ResponseWriter, r *http.Request, id EventId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List problems under an event (sort order ASC)
// (GET /events/{id}/problems)
func (_ Unimplemented) ListProblems(w http.ResponseWriter, r *http.Request, id EventId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a problem under an event
// (POST /events/{id}/problems)
func (_ Unimplemented) CreateProblem(w http.ResponseWriter, r *http.Request, id EventId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List competitions at a location
// (GET /locations/{locationId}/competitions)
func (_ Unimplemented) ListCompetitions(w http.ResponseWriter, r *http.Request, locationId LocationId, params ListCompetitionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a competition
// (POST /locations/{locationId}/competitions)
func (_ Unimplemented) CreateCompetition(w http.ResponseWriter, r *http.Request, locationId LocationId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a problem
// (PATCH /problems/{id})
func (_ Unimplemented) UpdateProblem(w http.ResponseWriter, r *http.Request, id ProblemId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RequestMagicLink operation middleware
func (siw *ServerInterfaceWrapper) RequestMagicLink(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestMagicLink(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCompetition operation middleware
func (siw *ServerInterfaceWrapper) GetCompetition(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCompetition(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCompetition operation middleware
func (siw *ServerInterfaceWrapper) UpdateCompetition(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCompetition(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCategories operation middleware
func (siw *ServerInterfaceWrapper) ListCategories(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCategories(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCategory operation middleware
func (siw *ServerInterfaceWrapper) CreateCategory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCategory(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEvents operation middleware
func (siw *ServerInterfaceWrapper) ListEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEvents(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEvent operation middleware
func (siw *ServerInterfaceWrapper) CreateEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CompetitionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateEvent operation middleware
func (siw *ServerInterfaceWrapper) UpdateEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id EventId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProblems operation middleware
func (siw *ServerInterfaceWrapper) ListProblems(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id EventId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProblems(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProblem operation middleware
func (siw *ServerInterfaceWrapper) CreateProblem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id EventId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProblem(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCompetitions operation middleware
func (siw *ServerInterfaceWrapper) ListCompetitions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "locationId" -------------
	var locationId LocationId

	err = runtime.BindStyledParameterWithOptions("simple", "locationId", chi.URLParam(r, "locationId"), &locationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCompetitionsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCompetitions(w, r, locationId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCompetition operation middleware
func (siw *ServerInterfaceWrapper) CreateCompetition(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "locationId" -------------
	var locationId LocationId

	err = runtime.BindStyledParameterWithOptions("simple", "locationId", chi.URLParam(r, "locationId"), &locationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCompetition(w, r, locationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProblem operation middleware
func (siw *ServerInterfaceWrapper) UpdateProblem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ProblemId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProblem(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/magic/request", wrapper.RequestMagicLink)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/competitions/{id}", wrapper.GetCompetition)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/competitions/{id}", wrapper.UpdateCompetition)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/competitions/{id}/categories", wrapper.ListCategories)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/competitions/{id}/categories", wrapper.CreateCategory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/competitions/{id}/events", wrapper.ListEvents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/competitions/{id}/events", wrapper.CreateEvent)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/events/{id}", wrapper.UpdateEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events/{id}/problems", wrapper.ListProblems)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/events/{id}/problems", wrapper.CreateProblem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/locations/{locationId}/competitions", wrapper.ListCompetitions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/locations/{locationId}/competitions", wrapper.CreateCompetition)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/problems/{id}", wrapper.UpdateProblem)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FzvctvIkX+VLlyqlqoFSdne5BK6UnW21944kdcqS779YOrEIdAAZjWYwc4MSHNVqsqne4CrPOE+ydX0",
	"DEhAJEXKtqRsNp8kEsD86T+//nVPg5dRospKSZTWRKPLqGKalWhR06cXqqzQcsuVfJ26L1I0ieaV+yIa",
	"tS/D+/evvx1EccTdhYrZIoojyUqMRhFPozjS+FPNNabRyOoa48gkBZbMjZkpXTIbjaK6pjvtonJPGau5",
	"zKOrqzh6OUNpdy0A3U13uowjlbBtomiu3bQAsXr+8xZyrNVUYLlLIpW/7Q5lcuUeNpWSBslenrP0Hf5U",
	"o7HuU6KkRUn/sqoS3O9++KNxK71sTfM7jVk0iv5juLLFob9qhi+1VtpP1d3pGybc8jAF7aeEqUoXoDRw",
	"OWOCp8B0XpdusEF0FUevlJ7yNEV590t7VtsCpXWjYgrT2oJUFpgQao4pWAUVard2sAU3wBL3GK3xe2Vf",
	"qVqmd7/Ed2hUrROklWVuTlrAe8lqWyjNf8Z7WMQbbgyXeVtnicbUiY4Jp7WrxhjJup4lCVbWLww/srIS",
	"6P5VF95wr+Ko0qpCbbm3RnfhsrHZqVICmYy8zTYG/8HddLY0bDX9ERPrBPEszzXmzC/0upP9Rc2dCvse",
	"ckyiNBpIVDnlEoFLq4C5j1Vf4AwFGMtkymU+gBOrNKZjyQxkGpFswMlyClyCLRC+ff7UGwU39DlhUkme",
	"MAEpJirFFNwzg7F8g7ZQad9UmPCMJ5BxFKmB3iTVqprEMJkjzwtr3L8Zl0yYc1rtOU8n8VhOpmjsuZwc",
	"ANMISooFlMgkl3lWCzcHGFUilDSLGYxldF24foB12bxSGprRR3CBWPkNlUwuwKpqTXAOmUoueVmX0ejR",
	"UhVcWsxRO124LW2ZyNTlubt8LifD1ayyLqeoQWUg1NwHBuPcLuUmYTrdPeM1iW2Z3IsY03N/+2QE84In",
	"RYhEQYP+mptyB5jGkZc2Wbd0S/sQmbqM4mi1ySiOrk0axY0mzjaMGIxg7/W76C8ECiesoCOHrTJBih8W",
	"SxrrZuGFb5jWbEHutuZcL5jFXOnFC43Mkg93bcsHp8v1/eha+DtYmlKMY+K49aQPX2vTGaXtudIp6nVB",
	"fIsZq4U3j0PgGaiSW4tkI9e3dg05aJWbsKMVg9f3xrrAchNutjHoKo4SklZ6zmwnNKfMYt/yEjeZFMrU",
	"3OqB5q6bV9ba4Sv/wFUceT/ZaeUCWYp6qphOz2fc8CkX3C52zXi0euq/Vw+54QKpOt9z+u22hTk3VvvB",
	"EqEM3ig5WQvBpi4Cdaxuy3iqQvl5wzmw5DI/T5TMeL7LB7pGfuKAVq+ChR8DeqZgFUKKlTMTUBImzSzO",
	"0SYHLSdoeVPrlnV/+p6V6IDXQR/hu3ae5bjDYgDPay5sn0szgolV1fnPSqIPUB/Rh6UUE7aYDOB4GSTU",
	"DLXmKRoQfIa0yGRlfR6izcRHqHWhiTpfX+P7d0d9wzIETlQj46hjqCX/qUYXnaAxqcHGIS3T9nY+ZSyz",
	"tbmFT534B67iqK7SW/r8NZAiJ2j7SPCAIJulw8cdYLqm5TXrW+5pqzu3BbWCoQ6IdXa3A0ebiLGOp21j",
	"2BMCPhsp9olC1+Jtl+35i1PHfVHwPAgNeixHmDKZxpCjTJ1Zok0GB4OxPCFXdcSQCDlNKhbgcAV++fs/",
	"HMfMMkgxcxR0XjALJbtAAwalwbF0Zu0k1fGTbRFyR9wjaV0T+8qqViM1gtql2i0k4NMD5X0Gve3RjAnx",
	"NotGHz4prp3FN/CUSVVPBU8mHbrymwltOwPSnlHgSM1RJ8xgDCnPuTUxMJlCsagKlOYplLWxQCAGc24L",
	"YKIqmKxL1DxxkaFi1qJ2I/3PB9b/+bD/p7Pwt392eRj/4cnV7754/NjPpjZEkpvtKdUss9fMaRPZXQ8a",
	"18PEBszf4f5U2/sisH5rt//cONC12/OGqewy4C3+sNmgO6N2Vfg6A4M2bjEkqhi06g6tcSinp0ScGNNg",
	"LL9/f3RESb+BcVQbXD7tooizjXE0gCO0BhgY1BwNlPxjSAvdms1Y9qaqFilq+BpMhZjC1+AAEWoXvEBJ",
	"P+CBjzq7cSDkmutbPVbGlzSdJ4ZSiRv5aZu2UXzbmdp/gv/5PHl9VW9qYXklOGqYFyhhGbFcWG+XhkJJ",
	"KEjRKstEi1v6asUtw2wjqm08K6x5h/O9Wga+9SoyUHYwgInhMhc4gT+TQmljMUz8Zty3pRdDuGTGcl4o",
	"g6DREMA0dTGnokkrqAfOvix10Cy0NTfwxnJGa+WhBL4JOIQiFrPT3NrVnZ0gkGvmfXDnsPumwWyKYl3y",
	"J4XStpWYgCnUXDqUTgR3dmKgh4N8AOPozaNxFMM4ev6f4+hgY65SKS43VX/eG0xhumgSr5CoPQWeS6XD",
	"pWV+RlGxScy2u3FjxXGkVW1xY9XsbeUxEQSXF5QXAt1swLoRQas59PJFCVw63Si9ONhUONsNJDfS2Thy",
	"+zpfCWfHjjb55dJ2GkV2Jt3hdSfLeN4YPwXgKI4cl3JD8pnzBGJqbgqmk4LPMN3lFO8pn1qX+zMhmgKx",
	"CioYwFspFs23lUZDNUsPrc2BCtM4liFJG8Cps0FkGhg0EvPPxy7LSAE/VoIn3NLVTSXjXzuj/6T61L9J",
	"+c2k/CFo9C3J86YStj/T6h5Eof+uHbRXx2vR2vEUNkNcO1yqSyb7GllKHkZ3QYnGsBwH8IbZpAhUDz9y",
	"Q2SDQHSO+gJQzlCoCgc7C0N+9k1IRYx8W1Z+a0/80ux5f7Z8I7+8N5LYTrQeDbYcMWwJNfuRva06vEU4",
	"eOrPACutZpxOGf1lphEa/F+D8wc3hU9PpG6Vityhqayrf20PmwPLmk5/KBQkTIJBn8i1othoLPurmtEv",
	"f/8HMLlwVL4XEr2nUAZUOXr5avhGGcYTN0DuEivB5AENUCLRz84IVBhROodwseAVMLtMz74yy1o6DdGE",
	"KGnDMGR0S2LrL6P2p9w+W3XDdPIEvw+X5vkpo1Xkc3RuE0N6w3KeHHF50epNacN2ybhwsO3X8V/h0iBR",
	"pQuU+NEplELF0Aul//jw8R824Lkf57pmTgsElqYaDWGAxgT5zCvJ8Fz2uSQ63CG6fqg4KtnHI5S5LaLR",
	"499/s8mlaHVbeXbFbOEnTbnGxBLnzqxLK+okQWOyWsAMNc9CZ8dgLN/UxsIUHTdHwaxbKw3TkwooSGIM",
	"UkGhjD3wpWfUM9RA/RvMohnLGWcwMSzDd2Fen0RkTAgDU5YQ958MU2YKslAqPYUOkJAVNurZIPidkY2E",
	"twkVQ9K4Lbbtnzrunw0u07wbkrNbZVT/XMmQ394Nsr7jGPRvle2lsmvaoQCX1JrbxQl5dOjoYRr1s9qh",
	"TfOpKRBFf/3hNIo3NJGUasoFwhCeHb92SE7tdvB2ahmXQDhw/PbkFIas4sPZoyGrbTEUKudyMpY9jbbW",
	"0sCEERidW3WBcgJfu0iRaTRF+OZgAH+heDYay8mz0KBGeDWC57ROGNeHh0+SH+eW/sFQXPJ4FY3CblbQ",
	"UVhbUU+FUhccmz2vb2+q1dyghiGcHD9b7e8ELbDaqpJZntBBnEdV1sLVsayYMXOlU6ANQy+Iwm//AJz0",
	"XGTqUzWEUHgxlr3Jdy9PYeg/9ukG2r+1FWXsX8MJK/GEW/zzEfvoPjpNIvQ4NXymodhKvZ5+d6tuz3M9",
	"PzdojD/ibfp0Kv43XPj2PC4ztS6Idy9PTkm/Liq/a3KNr3xwbhIdq1ly4ZIRh/SmriqlfSFUpt5SB2N5",
	"2upsC+2HKgOra1vQ2FPlwlWB8J1qokpv4uxeSybIhCZxiC6KVbyfqBRzpC42mdKDJzMUFv/GbdAV9CZz",
	"nA5NxYZGJ0PBp9eGqVC6kaieTVt2wn5XS5iU7ALBXXMz+CCao0TNLHptj6WpMIGkYDJH8xRevIaMcWFc",
	"MAsMyBN9aJ5zmCbQQKp5ZgdjOZbHBTMIjxAqVdXCRc+2TThvoa1RWf7Fu/ffAjPAgGrgKNO+VX2U6Vga",
	"wRNHKZgF/Ig64SakiFktBFS8QsEd4aMF//K//+cETFumD6cnqw9jSYaupKlL0v/BAMIiM0djTCgQlYxL",
	"p15a2VLH0PM14HgsQ/OxiaFdmDAxPV9LnnFMQ+vr8vm4w0XisWzU2mKzzuJPXoKxGlkZjN1yS1xhaZvO",
	"WqM4mqE23oQPB48Gh87hg8KjUfRkcDh44s/xCsI/D04k/qFeMcVKmQ0U67ugUjododJ1vzYrRke4Raoj",
	"NmKAE/eyKy44GMtnYs4WjvZ6FHx8+Jj4lBew76qmE//U9xILmBdoC9QOOaQimj2WNL67bcWeYzAKmARm",
	"LUsuULvE4CsLSIeXZL5JomrvkmN5xBZEuemK4CW3ZkRNmq+PobcsMTw+HJZceoukm1CT11FrQd8vovcE",
	"hvDo91ByGQPKTOkE06am6PzZGSnLGZfGhm7XoEAX0pet9VGg6UvaHlrU0djnKl18sbbktbTgqstuQk9x",
	"p8H98eHjLzb/sp15Y3t2qMCGe6DnRUyF1oJVFUpD4dWx6VyrWqbwU401Hgw64T0afTijBtKS6UV73DbM",
	"NEbbZB2W5caRO6fs6MwNN2whvRle8vTKbS5HkkBXed+hbfc/rsnv8IvJrz3NBhGehiQ03EIdEt8cPto2",
	"6nKZw04PPD30ze6Hlp37JP2lvL9zRKETJ6cL8AdCQchtyUZnjmS23sDZctC/umXYfUPn6ozwLNnAZt55",
	"uzYwyRfleckky1F/PQGtBG7J2QewYuljSY3i+1P1DX7tc4Hr1vHlHXv9RGQvz743y/SLSjdY5+FuQ2u9",
	"YvPpBv1k90Or12U+0wX8brtesN3+N4LNMPHtfyHp24g7R9zYF6vbPlO7y1b3PdW87E9c739fU/9qlQ+D",
	"SU5SsJJoaNboolTPpaBAKSg8O3lxcKeAtZFgfQperSGOr/QslXNHcNN9m2EvrHl0F1izMsKtRreA0ID7",
	"Lww4Xg/OoFd6vxXa+BzmRqR56W+5Z5TxvXJ7QIxfnvdf38+xeo/nwSAnvIe1GW7C8h4cbApk6blBaz8V",
	"bLyO7gZp2iezDwczwQq3WN1vCGCad843WPTNkOM9YZlH3c6mm5fh9+L6n2HOnrfduTk/OEPfas4NTfcN",
	"s//6BD2Y896mO2xKfDdGyuPmpnuOlU2D6B7RslniA8bGRpQNljTQcnc8vAMjdx0UG2XcDY50j3UfLjAu",
	"TW6rif2W2Hfz6yNdi74ZXRo7MsPL1Y+lXHUo+s0FgPaNax5x7XiPC4uauDH1+YW+6ongM3opVVX+5PFt",
	"6Wv3XCaiThGYEOEJ/9sFdNL2U42UZ4SDtuXbkbe2oWXP4dk94+U+QElQpbI20TExSJyjsZBxbezgV2Kl",
	"vgbS2oYDNLbEsS8Hs63fDPq8WsfOIsd9llUfHGo3ljhaCeWvBWf/dPc/snMi6hyY0MjSBXAJtQk2xdtx",
	"e1sJZd+UpiEwn5jUrH7R6n7SmnshJA+e2txASJrkJujtt3D+UC11vs2Ouwen3Y6oD2dX8WWnX+jDmbNV",
	"36eyiWBUWqV1Elyn1iK0HZnRcLhs2B9kYjFIcRa5wbuPG8tyLvPtz/ZTnN3wvHMBAe5ae4TRkEiWKJSx",
	"oz8e/vGQHC4I5HL775g5UKXOHt8+BIJnmCwSgdBr2pxif6ZM3awx/PWHUwhdXPQSV2BGdKa8vthT1by0",
	"umx1GYCvYsats4oYtraVuMUxa7GsrIGCyRxURn04BlvTdzR+dXb1/wEAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
