<script lang="ts">
  import { page } from '$app/state';
  import { goto } from '$app/navigation';
  import {
    getCardBatch,
    deleteCardBatch,
    listRoutes,
    cardBatchDownloadUrl,
    ApiClientError,
    type CardBatchShape,
    type RouteShape,
  } from '$lib/api/client';
  import { effectiveLocationId } from '$lib/stores/location.svelte';

  let batch = $state<CardBatchShape | null>(null);
  let routes = $state<Map<string, RouteShape>>(new Map());
  let loading = $state(true);
  let error = $state<string | null>(null);
  let deleting = $state(false);

  const batchId = $derived(page.params.id ?? '');
  const locId = $derived(effectiveLocationId());

  $effect(() => {
    if (!locId || !batchId) return;
    let cancelled = false;
    loading = true;
    error = null;
    getCardBatch(locId, batchId)
      .then(async (b) => {
        if (cancelled) return;
        batch = b;
        // Hydrate route names. The batch only stores IDs, so fetch the
        // route list for the location and pick the ones we need.
        // Capped at 500 — if a batch references >500 routes we silently
        // miss names for the overflow (rare; cards are capped much lower).
        try {
          const rs = await listRoutes(locId, { status: 'active', limit: 500 });
          if (cancelled) return;
          const m = new Map<string, RouteShape>();
          for (const r of rs.routes) m.set(r.id, r);
          routes = m;
        } catch {
          // best-effort; we'll show UUIDs if this fails
        }
      })
      .catch((err) => {
        if (cancelled) return;
        error = err instanceof ApiClientError ? err.message : 'Could not load batch.';
      })
      .finally(() => {
        if (!cancelled) loading = false;
      });
    return () => {
      cancelled = true;
    };
  });

  async function handleDelete() {
    if (!locId || !batchId) return;
    if (!confirm('Delete this card batch? The PDF can be regenerated by creating a new batch.')) return;
    deleting = true;
    try {
      await deleteCardBatch(locId, batchId);
      goto('/app/card-batches');
    } catch (err) {
      error = err instanceof ApiClientError ? err.message : 'Could not delete.';
      deleting = false;
    }
  }

  function fmtDate(iso: string): string {
    return new Date(iso).toLocaleString();
  }

  function themeLabel(t: string): string {
    return t.replace(/_/g, ' ');
  }
</script>

<svelte:head>
  <title>Card batch — Routewerk</title>
</svelte:head>

<div class="page">
  <a class="back" href="/app/card-batches">← Card batches</a>

  {#if loading}
    <p class="muted">Loading…</p>
  {:else if error}
    <p class="error">{error}</p>
  {:else if batch && locId}
    <header class="page-header">
      <div>
        <h1>Card batch</h1>
        <p class="meta-line">
          <span class="status-pill status-{batch.status}">{batch.status}</span>
          <span class="muted">· {themeLabel(batch.theme)} · created {fmtDate(batch.created_at)}</span>
        </p>
      </div>
      {#if batch.status !== 'failed'}
        <a class="btn-primary" href={cardBatchDownloadUrl(locId, batch.id)} target="_blank" rel="noreferrer">
          Download PDF
        </a>
      {/if}
    </header>

    {#if batch.status === 'failed' && batch.error_message}
      <div class="error">{batch.error_message}</div>
    {/if}

    <section class="card">
      <h2>Routes ({batch.route_ids.length})</h2>
      {#if batch.page_count > 0}
        <p class="muted page-count">{batch.page_count} page{batch.page_count === 1 ? '' : 's'} at 8-up</p>
      {/if}
      <ul class="route-list">
        {#each batch.route_ids as rid}
          {@const r = routes.get(rid)}
          <li>
            {#if r}
              <span class="color-chip" style="background:{r.color}"></span>
              <span class="grade">{r.grade}</span>
              {#if r.name}<span class="rname">{r.name}</span>{/if}
            {:else}
              <span class="color-chip placeholder"></span>
              <span class="muted">Route {rid.slice(0, 8)}…</span>
            {/if}
          </li>
        {/each}
      </ul>
    </section>

    <section class="card danger-zone">
      <h2>Danger zone</h2>
      <p class="muted">
        Deleting a batch frees the storage used by its rendered PDF. You
        can always create a new batch with the same route list.
      </p>
      <button class="danger" disabled={deleting} onclick={handleDelete}>
        {deleting ? 'Deleting…' : 'Delete batch'}
      </button>
    </section>
  {/if}
</div>

<style>
  .page {
    max-width: 56rem;
  }
  .back {
    display: inline-block;
    color: var(--rw-text-muted);
    text-decoration: none;
    font-size: 0.9rem;
    font-weight: 600;
    margin-bottom: 0.5rem;
  }
  .back:hover {
    color: var(--rw-accent);
  }
  .page-header {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    gap: 1rem;
    margin-bottom: 1.5rem;
  }
  h1 {
    font-size: 1.5rem;
    font-weight: 700;
    margin: 0 0 0.25rem;
    letter-spacing: -0.01em;
  }
  .meta-line {
    margin: 4px 0 0;
    font-size: 0.9rem;
    display: inline-flex;
    align-items: center;
    gap: 8px;
  }
  .status-pill {
    font-size: 0.7rem;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    padding: 2px 8px;
    border-radius: 4px;
    font-weight: 700;
  }
  .status-pending {
    background: rgba(245, 158, 11, 0.18);
    color: #92590a;
  }
  .status-ready {
    background: rgba(22, 163, 74, 0.12);
    color: #15803d;
  }
  .status-failed {
    background: #fef2f2;
    color: #b91c1c;
    border: 1px solid #fecaca;
  }
  .btn-primary {
    background: var(--rw-accent);
    color: var(--rw-accent-ink);
    padding: 0.55rem 1rem;
    border-radius: 8px;
    text-decoration: none;
    font-weight: 600;
    font-size: 0.9rem;
    border: 1px solid var(--rw-accent);
  }
  .hint {
    margin: 0 0 1rem;
    font-size: 0.9rem;
  }
  .card {
    background: var(--rw-surface);
    border: 1px solid var(--rw-border);
    border-radius: 12px;
    padding: 1.1rem 1.25rem;
    margin-bottom: 1rem;
  }
  .card h2 {
    font-size: 1rem;
    font-weight: 600;
    margin: 0 0 0.5rem;
  }
  .page-count {
    margin: 0 0 0.75rem;
    font-size: 0.85rem;
  }
  .route-list {
    list-style: none;
    padding: 0;
    margin: 0;
    display: flex;
    flex-direction: column;
    gap: 4px;
  }
  .route-list li {
    display: grid;
    grid-template-columns: 18px 3rem 1fr;
    align-items: center;
    gap: 10px;
    padding: 0.4rem 0;
    border-top: 1px solid var(--rw-border);
    font-size: 0.9rem;
  }
  .route-list li:first-child {
    border-top: none;
  }
  .color-chip {
    width: 14px;
    height: 14px;
    border-radius: 50%;
    border: 1px solid var(--rw-border-strong);
  }
  .color-chip.placeholder {
    background: var(--rw-surface-alt);
  }
  .grade {
    font-weight: 700;
  }
  .rname {
    color: var(--rw-text);
  }
  .danger-zone {
    border-color: #fde2e2;
    background: #fffafa;
  }
  .danger-zone h2 {
    color: #991b1b;
  }
  .muted {
    color: var(--rw-text-muted);
  }
  button {
    cursor: pointer;
    padding: 0.5rem 1rem;
    border-radius: 6px;
    border: 1px solid var(--rw-border-strong);
    background: var(--rw-surface);
    color: var(--rw-text);
    font-size: 0.9rem;
    font-weight: 600;
  }
  button.danger {
    color: #b91c1c;
    border-color: #fecaca;
  }
  button.danger:hover:not(:disabled) {
    background: #fef2f2;
  }
  .error {
    background: #fef2f2;
    border: 1px solid #fecaca;
    color: #991b1b;
    padding: 0.85rem;
    border-radius: 8px;
  }
</style>
