<script lang="ts">
  import { page } from '$app/state';
  import { goto } from '$app/navigation';
  import {
    getCardBatch,
    deleteCardBatch,
    updateCardBatch,
    retryCardBatch,
    listRoutes,
    cardBatchDownloadUrl,
    cardBatchCutlinesUrl,
    cardBatchPreviewUrl,
    CUTTER_PROFILES,
    ApiClientError,
    type CardBatchShape,
    type RouteShape,
  } from '$lib/api/client';
  import { effectiveLocationId } from '$lib/stores/location.svelte';

  let batch = $state<CardBatchShape | null>(null);
  let routes = $state<Map<string, RouteShape>>(new Map());
  let loading = $state(true);
  let error = $state<string | null>(null);
  let deleting = $state(false);

  // Edit-mode state. Pre-populates the selection from the current batch
  // when the user clicks Edit; saving PATCHes the route_ids.
  let editing = $state(false);
  let editSelected = $state<Set<string>>(new Set());
  let editSaving = $state(false);
  let editError = $state<string | null>(null);

  // Retry-state for the failure banner. Posts to .../retry which clears
  // the storage_key + resets status to pending. The next Download
  // re-renders against the same route list.
  let retrying = $state(false);
  let retryError = $state<string | null>(null);

  // First-card preview is a server-rendered PNG. The endpoint may 404
  // if every route in the batch was deleted; hide the figure on error.
  let previewBroken = $state(false);

  function openEdit() {
    if (!batch) return;
    editSelected = new Set(batch.route_ids);
    editError = null;
    editing = true;
  }

  function toggleEdit(id: string) {
    if (editSelected.has(id)) editSelected.delete(id);
    else editSelected.add(id);
    editSelected = new Set(editSelected);
  }

  async function saveEdit() {
    if (!locId || !batchId || editSaving) return;
    if (editSelected.size === 0) {
      editError = 'Pick at least one route.';
      return;
    }
    editSaving = true;
    editError = null;
    try {
      const updated = await updateCardBatch(locId, batchId, Array.from(editSelected));
      batch = updated;
      editing = false;
    } catch (err) {
      editError = err instanceof ApiClientError ? err.message : 'Save failed.';
    } finally {
      editSaving = false;
    }
  }

  const batchId = $derived(page.params.id ?? '');
  const locId = $derived(effectiveLocationId());

  $effect(() => {
    if (!locId || !batchId) return;
    let cancelled = false;
    loading = true;
    error = null;
    getCardBatch(locId, batchId)
      .then(async (b) => {
        if (cancelled) return;
        batch = b;
        // Hydrate route names. The batch only stores IDs, so fetch the
        // route list for the location and pick the ones we need.
        // Capped at 500 — if a batch references >500 routes we silently
        // miss names for the overflow (rare; cards are capped much lower).
        try {
          const rs = await listRoutes(locId, { status: 'active', limit: 500 });
          if (cancelled) return;
          const m = new Map<string, RouteShape>();
          for (const r of rs.routes) m.set(r.id, r);
          routes = m;
        } catch {
          // best-effort; we'll show UUIDs if this fails
        }
      })
      .catch((err) => {
        if (cancelled) return;
        error = err instanceof ApiClientError ? err.message : 'Could not load batch.';
      })
      .finally(() => {
        if (!cancelled) loading = false;
      });
    return () => {
      cancelled = true;
    };
  });

  async function handleRetry() {
    if (!locId || !batchId || retrying) return;
    retrying = true;
    retryError = null;
    try {
      const updated = await retryCardBatch(locId, batchId);
      batch = updated;
      previewBroken = false;
    } catch (err) {
      retryError = err instanceof ApiClientError ? err.message : 'Retry failed.';
    } finally {
      retrying = false;
    }
  }

  function cutterLabel(value: string): string {
    return CUTTER_PROFILES.find((p) => p.value === value)?.label ?? value;
  }

  async function handleDelete() {
    if (!locId || !batchId) return;
    if (!confirm('Delete this card batch? The PDF can be regenerated by creating a new batch.')) return;
    deleting = true;
    try {
      await deleteCardBatch(locId, batchId);
      goto('/card-batches');
    } catch (err) {
      error = err instanceof ApiClientError ? err.message : 'Could not delete.';
      deleting = false;
    }
  }

  function fmtDate(iso: string): string {
    return new Date(iso).toLocaleString();
  }

  function themeLabel(t: string): string {
    return t.replace(/_/g, ' ');
  }

  // Count batch route IDs that didn't resolve in the active-routes lookup.
  // Mirrors the HTMX "X of Y routes are no longer available" alert.
  // Routes can be missing for a few reasons: deleted from the DB, moved
  // to another location, or archived (the active-only filter on listRoutes
  // hides archived rows). Either way the PDF won't render a card for them,
  // so this is the right count to surface.
  const resolvedCount = $derived(
    batch ? batch.route_ids.filter((id) => routes.has(id)).length : 0,
  );
  const missingCount = $derived(batch ? batch.route_ids.length - resolvedCount : 0);
</script>

<svelte:head>
  <title>Card batch — Routewerk</title>
</svelte:head>

<div class="page">
  <a class="back" href="/card-batches">← Card batches</a>

  {#if loading}
    <p class="muted">Loading…</p>
  {:else if error}
    <p class="error">{error}</p>
  {:else if batch && locId}
    <header class="page-header">
      <div>
        <h1>Card batch</h1>
        <p class="meta-line">
          <span class="status-pill status-{batch.status}">{batch.status}</span>
          <span class="muted">
            · {batch.route_ids.length} card{batch.route_ids.length === 1 ? '' : 's'}
            · {batch.page_count} sheet{batch.page_count === 1 ? '' : 's'}
            · {themeLabel(batch.theme)}
            · created {fmtDate(batch.created_at)}
          </span>
        </p>
      </div>
      {#if batch.status !== 'failed'}
        <div class="header-actions">
          <a class="btn-primary" href={cardBatchDownloadUrl(locId, batch.id)} target="_blank" rel="noreferrer">
            Download PDF
          </a>
          <a
            class="btn-secondary"
            href={cardBatchCutlinesUrl(batch.id)}
            target="_blank"
            rel="noreferrer"
            title="Fallback DXF cut template for Silhouette Studio, if Cut-by-Color misbehaves on the PDF.">
            Cutlines DXF
          </a>
        </div>
      {/if}
    </header>

    {#if batch.status === 'failed'}
      <div class="alert-error">
        <div class="alert-error-body">
          <strong>Last render failed.</strong>
          {#if batch.error_message}<span class="muted">{batch.error_message}</span>{/if}
        </div>
        <button class="alert-action" disabled={retrying} onclick={handleRetry}>
          {retrying ? 'Retrying…' : 'Retry'}
        </button>
      </div>
      {#if retryError}<p class="error">{retryError}</p>{/if}
    {/if}

    {#if missingCount > 0 && resolvedCount > 0}
      <div class="alert-warn">
        <strong>
          {missingCount} of {batch.route_ids.length} routes are no longer available
        </strong>
        — they were deleted, archived, or moved to another location. The PDF
        will render only the {resolvedCount} remaining card{resolvedCount === 1 ? '' : 's'}.
      </div>
    {/if}

    <section class="meta-card">
      <dl class="meta-grid">
        <div><dt>Theme</dt><dd>{themeLabel(batch.theme)}</dd></div>
        <div><dt>Cutter</dt><dd>{cutterLabel(batch.cutter_profile)}</dd></div>
        <div><dt>Status</dt><dd>{batch.status}</dd></div>
      </dl>
      {#if batch.status !== 'failed' && resolvedCount > 0 && !previewBroken}
        <figure class="preview">
          <img
            src={cardBatchPreviewUrl(batch.id)}
            alt="Preview of the first card in this batch"
            loading="lazy"
            width="240"
            onerror={() => (previewBroken = true)} />
          <figcaption class="muted small">First card preview</figcaption>
        </figure>
      {/if}
    </section>

    <section class="card">
      <div class="routes-head">
        <h2>Routes ({editing ? editSelected.size : batch.route_ids.length})</h2>
        {#if !editing}
          <button class="ghost" onclick={openEdit}>Edit routes</button>
        {/if}
      </div>
      {#if editing}
        <p class="muted small">
          Toggle routes to add or remove. Save to update the batch — the next
          download re-renders against the new selection.
        </p>
        <ul class="route-list editable">
          {#each Array.from(routes.values()).sort((a, b) => a.grade.localeCompare(b.grade)) as r (r.id)}
            <li>
              <label class="route-row-edit">
                <input
                  type="checkbox"
                  checked={editSelected.has(r.id)}
                  onchange={() => toggleEdit(r.id)} />
                <span class="color-chip" style="background:{r.color}"></span>
                <span class="grade">{r.grade}</span>
                {#if r.name}<span class="rname">{r.name}</span>{/if}
              </label>
            </li>
          {/each}
        </ul>
        {#if editError}<p class="error">{editError}</p>{/if}
        <div class="edit-actions">
          <button class="primary" disabled={editSaving} onclick={saveEdit}>
            {editSaving ? 'Saving…' : 'Save routes'}
          </button>
          <button disabled={editSaving} onclick={() => (editing = false)}>
            Cancel
          </button>
        </div>
      {:else}
        <ul class="route-list">
          {#each batch.route_ids as rid}
            {@const r = routes.get(rid)}
            <li>
              {#if r}
                <span class="color-chip" style="background:{r.color}"></span>
                <span class="grade">{r.grade}</span>
                {#if r.name}<span class="rname">{r.name}</span>{/if}
              {:else}
                <span class="color-chip placeholder"></span>
                <span class="muted">Route {rid.slice(0, 8)}…</span>
              {/if}
            </li>
          {/each}
        </ul>
      {/if}
    </section>

    <section class="card danger-zone">
      <h2>Danger zone</h2>
      <p class="muted">
        Deleting a batch frees the storage used by its rendered PDF. You
        can always create a new batch with the same route list.
      </p>
      <button class="danger" disabled={deleting} onclick={handleDelete}>
        {deleting ? 'Deleting…' : 'Delete batch'}
      </button>
    </section>
  {/if}
</div>

<style>
  .page {
    max-width: 56rem;
  }
  .back {
    display: inline-block;
    color: var(--rw-text-muted);
    text-decoration: none;
    font-size: 0.9rem;
    font-weight: 600;
    margin-bottom: 0.5rem;
  }
  .back:hover {
    color: var(--rw-accent);
  }
  .page-header {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    gap: 1rem;
    margin-bottom: 1.5rem;
  }
  h1 {
    font-size: 1.5rem;
    font-weight: 700;
    margin: 0 0 0.25rem;
    letter-spacing: -0.01em;
  }
  .meta-line {
    margin: 4px 0 0;
    font-size: 0.9rem;
    display: inline-flex;
    align-items: center;
    gap: 8px;
  }
  .status-pill {
    font-size: 0.7rem;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    padding: 2px 8px;
    border-radius: 4px;
    font-weight: 700;
  }
  .status-pending {
    background: rgba(245, 158, 11, 0.18);
    color: #92590a;
  }
  .status-ready {
    background: rgba(22, 163, 74, 0.12);
    color: #15803d;
  }
  .status-failed {
    background: #fef2f2;
    color: #b91c1c;
    border: 1px solid #fecaca;
  }
  .header-actions {
    display: inline-flex;
    gap: 6px;
    flex-shrink: 0;
  }
  .btn-primary {
    background: var(--rw-accent);
    color: var(--rw-accent-ink);
    padding: 0.55rem 1rem;
    border-radius: 8px;
    text-decoration: none;
    font-weight: 600;
    font-size: 0.9rem;
    border: 1px solid var(--rw-accent);
  }
  .btn-secondary {
    background: var(--rw-surface);
    color: var(--rw-text);
    padding: 0.55rem 1rem;
    border-radius: 8px;
    text-decoration: none;
    font-weight: 600;
    font-size: 0.9rem;
    border: 1px solid var(--rw-border-strong);
  }
  .btn-secondary:hover {
    border-color: var(--rw-accent);
    color: var(--rw-accent);
  }
  .alert-error {
    display: flex;
    align-items: center;
    gap: 1rem;
    background: #fef2f2;
    border: 1px solid #fecaca;
    color: #991b1b;
    padding: 0.85rem 1rem;
    border-radius: 8px;
    margin: 0 0 1rem;
  }
  .alert-error-body {
    flex: 1;
    display: flex;
    flex-direction: column;
    gap: 2px;
    font-size: 0.9rem;
  }
  .alert-error .muted {
    color: #b45050;
    font-weight: 400;
  }
  .alert-action {
    background: var(--rw-surface);
    color: #991b1b;
    border: 1px solid #fecaca;
    padding: 0.4rem 0.85rem;
    border-radius: 6px;
    font-weight: 600;
    font-size: 0.85rem;
    cursor: pointer;
    flex-shrink: 0;
  }
  .alert-action:hover:not(:disabled) {
    background: #fee2e2;
  }
  .alert-action:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  .alert-warn {
    background: #fffbeb;
    border: 1px solid #fde68a;
    color: #92400e;
    padding: 0.85rem 1rem;
    border-radius: 8px;
    margin: 0 0 1rem;
    font-size: 0.9rem;
  }
  .meta-card {
    background: var(--rw-surface);
    border: 1px solid var(--rw-border);
    border-radius: 12px;
    padding: 1rem 1.25rem;
    margin-bottom: 1rem;
    display: flex;
    align-items: flex-start;
    gap: 1.5rem;
  }
  .meta-grid {
    flex: 1;
    margin: 0;
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(7rem, 1fr));
    gap: 0.75rem 1.5rem;
  }
  .meta-grid > div {
    display: flex;
    flex-direction: column;
    gap: 2px;
  }
  .meta-grid dt {
    font-size: 0.7rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: var(--rw-text-muted);
  }
  .meta-grid dd {
    margin: 0;
    font-size: 0.9rem;
    font-weight: 500;
    text-transform: capitalize;
  }
  .preview {
    margin: 0;
    flex-shrink: 0;
    text-align: center;
  }
  .preview img {
    max-width: 240px;
    border: 1px solid var(--rw-border);
    border-radius: 6px;
    background: var(--rw-surface-alt);
  }
  .preview figcaption {
    margin-top: 4px;
  }
  .hint {
    margin: 0 0 1rem;
    font-size: 0.9rem;
  }
  .card {
    background: var(--rw-surface);
    border: 1px solid var(--rw-border);
    border-radius: 12px;
    padding: 1.1rem 1.25rem;
    margin-bottom: 1rem;
  }
  .card h2 {
    font-size: 1rem;
    font-weight: 600;
    margin: 0 0 0.5rem;
  }
  .page-count {
    margin: 0 0 0.75rem;
    font-size: 0.85rem;
  }
  .route-list {
    list-style: none;
    padding: 0;
    margin: 0;
    display: flex;
    flex-direction: column;
    gap: 4px;
  }
  .route-list li {
    display: grid;
    grid-template-columns: 18px 3rem 1fr;
    align-items: center;
    gap: 10px;
    padding: 0.4rem 0;
    border-top: 1px solid var(--rw-border);
    font-size: 0.9rem;
  }
  .route-list li:first-child {
    border-top: none;
  }
  .color-chip {
    width: 14px;
    height: 14px;
    border-radius: 50%;
    border: 1px solid var(--rw-border-strong);
  }
  .color-chip.placeholder {
    background: var(--rw-surface-alt);
  }
  .grade {
    font-weight: 700;
  }
  .rname {
    color: var(--rw-text);
  }
  .routes-head {
    display: flex;
    justify-content: space-between;
    align-items: baseline;
    gap: 12px;
    margin-bottom: 4px;
  }
  .routes-head button.ghost {
    background: transparent;
    border: 1px solid var(--rw-border-strong);
    color: var(--rw-text);
    padding: 0.35rem 0.85rem;
    border-radius: 6px;
    font-size: 0.85rem;
    font-weight: 600;
    cursor: pointer;
  }
  .routes-head button.ghost:hover {
    border-color: var(--rw-accent);
  }
  .small {
    font-size: 0.85rem;
    margin: 0 0 0.75rem;
  }
  .route-list.editable {
    max-height: 24rem;
    overflow-y: auto;
    border: 1px solid var(--rw-border);
    border-radius: 8px;
    padding: 0;
  }
  .route-list.editable li {
    grid-template-columns: 22px 18px 3rem 1fr;
    border-top: 1px solid var(--rw-border);
    padding: 0.4rem 0.7rem;
  }
  .route-row-edit {
    display: contents;
    cursor: pointer;
  }
  .edit-actions {
    margin-top: 0.85rem;
    display: flex;
    gap: 8px;
  }
  .edit-actions button {
    padding: 0.5rem 1rem;
    border-radius: 6px;
    border: 1px solid var(--rw-border-strong);
    background: var(--rw-surface);
    color: var(--rw-text);
    font-weight: 600;
    font-size: 0.9rem;
    cursor: pointer;
  }
  .edit-actions button.primary {
    background: var(--rw-accent);
    color: var(--rw-accent-ink);
    border-color: var(--rw-accent);
  }
  .edit-actions button:disabled {
    opacity: 0.55;
    cursor: not-allowed;
  }
  .danger-zone {
    border-color: #fde2e2;
    background: #fffafa;
  }
  .danger-zone h2 {
    color: #991b1b;
  }
  .muted {
    color: var(--rw-text-muted);
  }
  button {
    cursor: pointer;
    padding: 0.5rem 1rem;
    border-radius: 6px;
    border: 1px solid var(--rw-border-strong);
    background: var(--rw-surface);
    color: var(--rw-text);
    font-size: 0.9rem;
    font-weight: 600;
  }
  button.danger {
    color: #b91c1c;
    border-color: #fecaca;
  }
  button.danger:hover:not(:disabled) {
    background: #fef2f2;
  }
  .error {
    background: #fef2f2;
    border: 1px solid #fecaca;
    color: #991b1b;
    padding: 0.85rem;
    border-radius: 8px;
  }
</style>
